### ISSUE TITLE
UI — Populate all links in footer

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#103]
Add links

- [x] Contribute - https://github.com/YACS-RCOS/yacs.n
- [x] Feature Request - https://github.com/YACS-RCOS/yacs.n/issues/new?assignees=&labels=bug&template=bug_report.md&title=Bug+—+Something+made+an+oopsie
- [x] Submit Bug Report Template - https://github.com/YACS-RCOS/yacs.n/issues/new?assignees=&labels=Feature+Request&template=feature-request.md&title=Feature+Request+-+Make+YACS+Great
- [x] Add a link to general cookie policy
- [x] Add a link to general terms of use, find something online to link to

Remove Link:
- [x] Remove EULA

**Comment by marchdan** [comment]
@jshom Should the feature request default say something made an oopsie? Or someone made an oppsie?

**Comment by jshom** [comment]
@marchdan Whatever you feel is right :)

**Comment by marchdan** [comment]
I need to know what cookies we are storing. There is no one policy online because it seems to be website specific. @jshom
