### ISSUE TITLE
Incorrect course start times

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#11]
Certain courses have incorrect start times
Judging from a few instances, it seems that only courses with pm start times are affected.

The issue causes courses with pm start times to be parsed as am start times. 

E.g. MGMT-6690 Negotiation
```json
{
"crn":"15674",
"day_of_week":2,
"section":"01",
"semester":"SUMMER 2020",
"time_end":"17:20:00",
"time_start":"02:00:00"
}
```

**Comment by marchdan** [comment]
Issue is in the source data. Fixing now
