### ISSUE TITLE
Bug — Username cookie still being stored at logout

### ISSUE THREAD

**Issue by marchdan** [YACS-RCOS/yacs.n#124]
**Describe the bug**
> The `userName` cookie is still being stored even after user logout. This cookie has no helpful purpose if the user is logged out.

**To Reproduce**
1. Log-in to the system
2. Check your cookies to check that userName is still stored.
3. Log-out of the system
4. Check your cookies to see that userName is still stored

**Expected behavior**
`userName` will still be stored.

**Desktop (please complete the following information):**
 - OS: Ubunutu 18.04 LTS
 - Browser Chrome incognito

**Additional context**
Storing information such as userID for longer than a user session might be helpful if we want to ever have auto-login or a similar feature.

**Comment by 123joshuawu** [comment]
Should be fine? Unless it's disruptive or something, it'll timeout eventually eh?

**Comment by CoreyBuckley** [comment]
I agree with Josh. There's no real harm in the cookie staying there since there's an expire period on it. I'm guessing it's like a week or so.

**Comment by marchdan** [comment]
I was more referencing if there is a more useful cookie to be leaving in storage?

**Comment by marchdan** [comment]
Closing for now. Can be reopened if it ever becomes an issue
