### ISSUE TITLE
Bug — UX Tweaks

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#126]
**Describe the bug**
Collection of UX tweaks we should add to make YACS.N ready for v0 release.
Given there are a few, will not make an issue for each. Tick the checkmark for each when each is done.

- [x] Click the class to add it to selected courses
> ![Screen Shot 2020-04-24 at 12 26 29 PM](https://user-images.githubusercontent.com/11034221/80244632-44928e00-8637-11ea-8340-cf8d69e67b70.jpg)
- [x] Click the header of the class to open/close in "selected courses"
> ![Screen Shot 2020-04-24 at 12 10 49 PM](https://user-images.githubusercontent.com/11034221/80244754-80c5ee80-8637-11ea-8701-6c28d814cd02.jpg)
- [x] Downwards tick should change to upwards tick when opened/closed in "Selected Courses"
> ![Screen Shot 2020-04-24 at 12 13 24 PM](https://user-images.githubusercontent.com/11034221/80244845-ae129c80-8637-11ea-8e77-d247ea5c04d1.jpg)
- [x] Show that no courses are selected, please add courses from the search
> ![Screen Shot 2020-04-24 at 12 13 51 PM](https://user-images.githubusercontent.com/11034221/80244908-c682b700-8637-11ea-89d1-0120b194c013.jpg)
- [x] "Other semester" buttons should be text, either bold or greyed out if not-selected, currently it draws too much attention
![Screen Shot 2020-04-24 at 12 24 17 PM](https://user-images.githubusercontent.com/11034221/80245177-3a24c400-8638-11ea-93b2-677f110d207c.jpg)

**Comment by marchdan** [comment]
![other-semesters](https://user-images.githubusercontent.com/35609442/80248729-86730280-863e-11ea-8459-8f8c416dd8cc.png)

**Comment by jshom** [comment]
@marchdan can you create pr for this
