### ISSUE TITLE
Scheduling — On course add, add first possible section

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#127]
**Job**
When starting to build a section, I want to see my schedule show up faster.

**Describe a possible solution**
On add course from the course search:
Add the first section to the schedule render that would not cause a schedule conflict.
(If no section can be added immediately, create vue notification but still add to selected courses)

**Context**
Many courses in 2000+ don't have much variety with schedule times, so this would reduce two clicks to see the course on your schedule.

**Expected Behavior**
When I clicked data mining, I would expect the class to show up [instead of going to course selections and clicking the first section]. (Or notify me that there's a conflict). 
![Kapture 2020-04-24 at 14 36 39](https://user-images.githubusercontent.com/11034221/80245642-0c8c4a80-8639-11ea-84dd-d24a99170dfe.gif)

**Comment by marchdan** [comment]
This would need to also have rollback, so that if a second course is added and all of its sections conflict with the current section of the previous course, it looks for a solution. 

This could be solved by adding all sections to start with and removing sections as conflicts happen?

**Comment by 123joshuawu** [comment]
> if a second course is added and all of its sections conflict with the current section of the previous course

then that would be a schedule conflict and there would no schedules?  
I believe that's how its done in YACS rn

**Comment by jshom** [comment]
> > if a second course is added and all of its sections conflict with the current section of the previous course
> 
> then that would be a schedule conflict and there would no schedules?
> I believe that's how its done in YACS rn

Almost, instead of showing an empty schedule on conflict, use the notification. No one likes things disappearing

**Comment by jshom** [comment]
> This would need to also have rollback, so that if a second course is added and all of its sections conflict with the current section of the previous course, it looks for a solution.
> 
> This could be also solved by adding all sections to start with and removing sections as conflicts happen?

Rollback would start to go into auto chedule generation, let’s worry about this later. This is meant to add ux improvement without us spending a lot of time on a schedule search problem.

**Comment by marchdan** [comment]
> > if a second course is added and all of its sections conflict with the current section of the previous course
> 
> then that would be a schedule conflict and there would no schedules?
> I believe that's how its done in YACS rn

No, you would find a different section of the previous course that doesn't conflict
