### ISSUE TITLE
Bug — Title and Favicon

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#128]
**Describe the bug**
- [ ] The page title of / is "yacs-web" -> "YACS"
- [ ] The favicon should be the yacs logo, you can use the github link in img source
`https://user-images.githubusercontent.com/11034221/80246576-a274a500-863a-11ea-8d18-93ef2c095b7b.jpg`
![Screen Shot 2020-04-24 at 2 47 48 PM](https://user-images.githubusercontent.com/11034221/80246576-a274a500-863a-11ea-8d18-93ef2c095b7b.jpg)

**Comment by marchdan** [comment]
@jshom should this logo also be in the header instead of "YACS"?
