### ISSUE TITLE
Bug - UX Search

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#129]
**Describe the bug**
1. Show that no course results are shown
> Example below, edited image as example
> ![Screen Shot 2020-04-24 at 2 51 22 PM](https://user-images.githubusercontent.com/11034221/80247114-8a515580-863b-11ea-80a3-b7053461b8ab.jpg)
2. Search for "CSCI" should return computer science classes, should not be forced to use department filter
> 
![Screen Shot 2020-04-24 at 2 54 03 PM](https://user-images.githubusercontent.com/11034221/80247212-abb24180-863b-11ea-8d21-1aa4bb7b6f96.jpg)

**Comment by 123joshuawu** [comment]
This search might be a technical debt issue as well. The first task is pretty straightforward but I'm having trouble figuring out a good way to make the search work out.
