### ISSUE TITLE
Bug — Slow loading of course data

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#136]
**Describe the bug**
Takes 1.62 seconds on my net to load /class
Make it load within 0.3 - Great, 0.4 - ok seconds.

**Info/Perf Analysis**
Current end to end is around/above: 1.62 seconds
- [x] Adding index on semester turned out not to help much
- [ ] Lets try caching the result in nginx and see what performance we get

Lets not write code before we test out options manually (well, write minimum to test) :)

**Comment by 123joshuawu** [comment]
Since the only changes to the courses are coming in through the csvs, instead of running the query every time we retrieve courses, is it possible to run the query when we input the csv, store the results and serve that?

**Comment by jshom** [comment]
closing due to caching fix from #172
