### ISSUE TITLE
Bug — Course Search Input Delay

### ISSUE THREAD

**Issue by CoreyBuckley** [YACS-RCOS/yacs.n#137]
**Describe the bug**
When I search for a course name in the course list, there is a noticeable impact on the performance of the component. If you keep backspacing an entered course name, the keystrokes are buffered until it finishes 'undoing' the filter. 

**To Reproduce**
1. Have Summer 2020 loaded & go to Schedule page
2. Type, for example, "Com"
3. Backspace 3 times. Notice how there is a delay in input when you reach "Co"

**Expected behavior**
No noticeable delay.

**Screenshots**
![searchDelay](https://user-images.githubusercontent.com/28029704/80263723-89321f80-865f-11ea-8844-5a9ca10382f2.gif)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 80.0.3987.163 64-bit

**Additional context**
Could only apply the filter if there's > 2 characters?

**Comment by 123joshuawu** [comment]
Interesting, I think this may just be computed list filtering performance issues but summer is way smaller than the other semesters.
