### ISSUE TITLE
Bug — + Btn doesn't work on course list

### ISSUE THREAD

**Issue by CoreyBuckley** [YACS-RCOS/yacs.n#139]
**Describe the bug**
As of master 6a5095ebbb6ed862407d9ce57cb757c858c16a47, clicking the '+' button on a class listing does not add a class. (I think it's triggering the event twice, so it adds the class and then removes it)

**To Reproduce**
1. Go to Schedule
2. Click on '+' for a class listing 
3. Observe

**Expected behavior**
Button should add class

**Screenshots**

![Kapture 2020-04-24 at 21 41 47](https://user-images.githubusercontent.com/28029704/80268553-02d50800-8676-11ea-8851-5686a049263e.gif)

**Desktop (please complete the following information):**
 - OS: Win 10 & Mac OS

**Comment by 123joshuawu** [comment]
I'm guessing this is a `click.stop` issue, i think it is working in #138
