### ISSUE TITLE
Schedule conflict pop ups

### ISSUE THREAD

**Issue by smgibson19** [YACS-RCOS/yacs.n#143]
**Describe the bug**
The Schedule conflict red pop up boxes do not go away on their own and can accumulate.

**To Reproduce**
1. Go to course search
2. Click several classes, doesn't matter which, until course conflicts come up
3. You will see the red pop up boxes in the corner, if not manually x'ed out they build up over time and don't go away. 
4. Eventually they run off of the page, but are still there

**Expected behavior**
I think those boxes should pop up, and after a certain time vanish on their own, it could slow performance down if too many of those are open and people don't close them. 

**Additional context**
This isn't a critical issue, just something that I noticed while testing the site

**Comment by 123joshuawu** [comment]
HEhe set this when I was developing and forgot to change it back oops
