### ISSUE TITLE
Minor Issues Clicking Box to Add a Course (Lag/ Click box Range)

### ISSUE THREAD

**Issue by smgibson19** [YACS-RCOS/yacs.n#144]
**Describe the bug**

**To Reproduce**
1. Go to Course Schedule
2. Click on multiple classes in succession as if adding them all to your schedule
4. (Lag) At least from my device, I'm not sure if it is my laptop or the site in general, but it takes a bit for each class to load. It doesn't show it clicked for a bit, so I re-click it and accidentally un-selects it.
5. (Click box) while I was clicking classes, not all of the ones I clicked on went onto the schedule. I realized it was because the space above and below the name of the class isn't clickable space. 

**Expected behavior**
Less lag and to be able to click anywhere within the boundary of the lines to select the course. 

**Additional context**
I'm not sure if these are intentional things that are supposed to be like that, but I just noticed it was kind of slow and it was kind of annoying to select things quickly.

**Comment by marchdan** [comment]
Should already be able to click anywhere in the box to add. I can check out when I have a chance

**Comment by 123joshuawu** [comment]
The lag is related to #148
