### ISSUE TITLE
Font bold/Unbold under Other Semesters

### ISSUE THREAD

**Issue by smgibson19** [YACS-RCOS/yacs.n#145]
**Job**
I was trying to see what semester I had selected and which ones I could pick, but the bolded options under "Other Semesters" are the ones that aren't selected, and the not bold option is what is currently selected.

**Describe a possible solution**
I think it will be clearer and make more sense to have it the opposite; have the selected semester be in bold and the other options be normal text

**Context**
This is just an aesthetic fix, and it would make more logical sense to have the selected item stand out bold compared to the not selected items.

**Comment by marchdan** [comment]
@jshom Thoughts? Might make more sense to not display current semester at all under “Other Semester” and then un-bold the semesters listed.

**Comment by jshom** [comment]
I like the idea, lets remove current semester from other and leave the styling the same.
