### ISSUE TITLE
Scheduling — Save selected semester schedule for user

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#15]
Fetch CRN selection:
- if logged in, fetch from db
- otherwise, check cookies

note: this is parametrized per semester

**Comment by jshom** [comment]
Table: [user_id, semester] -> [course id].
Create schema in ./src/data/schema/student_course_selection.sql
add to `build.sh`
Add wrapper in ./src/db/student_course_selection.py
with:
- update_selection
- get_selection

**Comment by marchdan** [comment]
@jshom This the one you needed me to take over? I don't see Yuze as being assigned

**Comment by marchdan** [comment]
> Table: [user_id, semester] -> [course id].
> Create schema in ./src/data/schema/student_course_selection.sql
> add to `build.sh`
> Add wrapper in ./src/db/student_course_selection.py
> with:
> 
> * update_selection
> * get_selection

@jshom A couple questions:
- Is course_id a third column in this schema?
- Should the wrapper be in src/db/... or src/api/db/... ?

**Comment by jshom** [comment]
*Is course_id a third column in this schema?*
**Yes**
*Should the wrapper be in src/db/... or src/api/db/... ?*
**Yes src/api/db**

**Comment by marchdan** [comment]
Do we want this to be:
```
user_id | FALL 2020 | [12345, 24680, ...]
```
or
```
user_id | FALL 2020 | 12345
user_id | FALL 2020 | 24680
...
```
?

**Comment by marchdan** [comment]
@jshom ^^

**Comment by jshom** [comment]
2nd

**Comment by marchdan** [comment]
db functionality written. Debating whether to have update selection do both removes and adds based on a flag, or to split into two functions
