### ISSUE TITLE
Graduation Requirements

### ISSUE THREAD

**Issue by DarknessUnder** [YACS-RCOS/yacs.n#154]
Some way of inputting graduation requirements (degree templates?)
Allow users to create schedules for multiple semesters
Database schema(s) for storing graduation requirements
Admin panel addition for inputting graduation requirements
Student side some graduation dashboard? Show progress, courses need to take, taken, overview, etc.

**Comment by 123joshuawu** [comment]
Try to adhere to the issue template as best as you can next time, otherwise looks good!

**Comment by 123joshuawu** [comment]
Closing for new semester, feel free to reopen
