### ISSUE TITLE
Feature Request — Course Exploration

### ISSUE THREAD

**Issue by IkeLyons** [YACS-RCOS/yacs.n#156]
**Job**
Add a course exploration page, similar to the old yacs homepage, that will allow users to browse all classes. This could also be the home to features such as finding free electives that fit into the users class schedule.

**Describe a possible solution**
1) I believe the easiest way to give this part of the site a home would be to place it directly next to the "course search" tab. This way the course search and course explorer, presumably the two ways users are going to be finding classes, will be easily accessible and next to each other. This will also allow the users schedule to stay visible. 
2) There are other ways to implement this as well, such as giving the course explorer its own page completely separate from the main page. These would likely be harder to do and require more of a redesign, but I'm open to that if its the best idea. 

**Context**
Talked about during webex meeting.

**Comment by jshom** [comment]
Closing by sub issues #192 #191
