### ISSUE TITLE
RPI — Add school column to RPI data csvs

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#162]
**Job**
Each course is of a school (e.g. School of Science)

**Describe a possible solution**
RPI csv parser should output a new column `school` that contains the school of a course

**Context**

**Comment by marchdan** [comment]
@123joshuawu We have no specific way to put school in the parser, it is not in the class hours schedule. We can use the course_department label in the csv to determine it. Should this be done in the parser, or do we want to do it on the backend when the data is imported from the CSV?

**Comment by 123joshuawu** [comment]
@marchdan I think it should be done in the parser
