### ISSUE TITLE
Distribution — RPI:Parsing Errors

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#17]
**tp column fix**
We are ignoring courses that include the TP column
example course:
- ADMIN-1824

**change parsing method**
do not rely on length, ignoring courses that are not of length 5 and 11, take into account all fields and edge cases.

**Comment by marchdan** [comment]
Working to make parser more robust. Will post example of new parse when completed

**Comment by marchdan** [comment]
Snippet from new CSV
`
STUDENT SUCCESS LABS | LEC | 0 | W | 1:00PM | 1:50PM | Trzepacz | 120 | 0 | 120 | ADMN | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15486 | 1824 | 1
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SUMMER ADMINIST REGISTRATION | LEC | 0 |   | **TBA** |   | Grega | 625 | 7 | 618 | ADMN | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 14908 | 6600 | 1
MATERIALS AND DESIGN | LEC | 2 | R | 10:30AM | 12:35PM | Staff | 12 | 2 | 10 | ARCH | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15343 | 2510 | 1
ARCHITECTURAL DESIGN STUDIO 5 | LEC | 5 | MWR | 2:00PM | 5:50PM | Staff | 32 | 32 | 0 | ARCH | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15413 | 4770 | 1
MASTER'S THESIS | LEC | 1-12 |   | **TBA** |   | Staff | 10 | 0 | 10 | ARCH | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15031 | 6990 | 3
MASTER'S THESIS | LEC | 1-12 |   | **TBA** |   | Staff | 0 | 0 | 0 | ARCH | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15057 | 6990 | 4
ARCHITECTURE DISSERTATION | LEC | 1-15 |   | **TBA** |   | Figueiro | 10 | 0 | 10 | ARCH | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15240 | 9990 | 1
ART HISTORY | LEC | 4 | MR | 10:30AM | 12:35PM | Wille Kiel | 60 | 49 | 11 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15371 | 1050 | 1
MUSIC AND TECHNOLOGY 1 | STU | 4 | MR | 8:00AM | 10:05AM | Staff | 19 | 19 | 0 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15688 | 2020 | 1
CHAMBER MUSIC ENSEMBLE |   | 1 | W | 1:30PM | 3:35PM | Staff | 25 | 9 | 16 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15736 | 2350 | 1
PRIVATE MUSIC LESSONS: VIOLIN |   | 1 |   | **TBA** |   | Morey/Fisher-Loc | 9 | 1 | 8 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15739 | 2750 | 1
PRIVATE MUSIC LESSONS: VIOLA |   | 1 |   | **TBA** |   | Morey/Fisher-Loc | 9 | 0 | 9 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15740 | 2750 | 2
PRIVATE MUSIC LESSONS: FLUTE |   | 1 |   | **TBA** |   | Gerbino/Fisher-Loc | 9 | 1 | 8 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15741 | 2750 | 3
PRIVATE MUSIC LESSONS: OBOE |   | 1 |   | **TBA** |   | Gerbino/Fisher-Loc | 9 | 0 | 9 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15742 | 2750 | 4
PRIVATE MUSIC LESSONS:CLARINET |   | 1 |   | **TBA** |   | Gerbino/Fisher-Loc | 9 | 0 | 9 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15743 | 2750 | 5
PRIVATE MUSIC LESSONS: SAX |   | 1 |   | **TBA** |   | Gerbino/Fisher-Loc | 9 | 1 | 8 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15744 | 2750 | 6
PRIVATE MUSIC LESSONS: HARP |   | 1 |   | **TBA** |   | Caldicott/Fisher-Loc | 9 | 0 | 9 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15745 | 2750 | 7
PRIVATEMUSICLESSONS:PERCUSSION |   | 1 |   | **TBA** |   | Francis/Fisher-Loc | 9 | 2 | 7 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15746 | 2750 | 8
PRIVATE MUSIC LESSONS: VOICE |   | 1 |   | **TBA** |   | Harrigan/Fisher-Loc | 9 | 2 | 7 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15747 | 2750 | 9
PRIVATE MUSIC LESSONS: TRUMPET |   | 1 |   | **TBA** |   | Williams/Fisher-Loc | 9 | 2 | 7 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15748 | 2750 | 10
GAME SOUND & MUSICAL PLAY | LEC | 4 | MR | 8:00AM | 10:05AM | Galloway | 19 | 13 | 6 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15691 | 2965 | 1
SOUND ECOLOGY | LEC | 4 | MR | 10:30AM | 12:35PM | Galloway | 19 | 1 | 18 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15692 | 2966 | 1
VIDEO ART | STU | 4 | MR | 1:30PM | 3:35PM | Wille Kiel | 16 | 11 | 5 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15693 | 2967 | 1
STARS, GALAXIES AND THE COSMOS | LEC | 4 | MR | 8:00AM | 10:05AM | Martin | 0 | 40 | -40 | ASTR | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15483 | 1960 | 1
EARTH AND SKY | LEC | 4 | TF | 8:00AM | 10:05AM | Martin | 0 | 50 | -50 | ASTR | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15348 | 2120 | 1
MOLECULAR BIOCHEMISTRY I | LEC | 4 | MR | 10:30AM | 12:35PM | Fraser | 50 | 16 | 34 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15338 | 4760 | 1
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Wang | 10 | 0 | 10 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15170 | 6990 | 1
DISSERTATION | LEC | 1-15 |   | **TBA** |   | Bystroff | 10 | 0 | 10 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15171 | 9990 | 1
DISSERTATION | LEC | 1-15 |   | **TBA** |   | Swank | 0 | 0 | 0 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15172 | 9990 | 2
DISSERTATION | LEC | 1-15 |   | **TBA** |   | Linhardt | 10 | 0 | 10 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15173 | 9990 | 3
DISSERTATION | LEC | 1-15 |   | **TBA** |   | Wang | 10 | 0 | 10 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15174 | 9990 | 4
INTRODUCTION TO CELL BIOLOGY | LEC | 4 | MR | 10:30AM | 12:35PM | Klein | 16 | 1 | 15 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15671 | 2120 | 1
INTRODUCTION TO CELL BIOLOGY | LAB | 4 | T | 12:30AM | 4:30PM | Klein | 1 | 15 | BIOL | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15671 | 2120 | 1
MICROBIOLOGY LABORATORY | LAB | 6 | T | 1:00PM | 5:50PM | Bonocora | 16 | 4 | 12 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15411 | 4320 | 1
MICROBIOLOGY LABORATORY | REC | 6 | R | 1:00PM | 2:50PM | Bonocora | 4 | 12 | BIOL | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15411 | 4320 | 1
MOLECULAR BIOLOGY LAB | LAB | 6 | T | 1:00PM | 5:50PM | Rutledge | 16 | 16 | 0 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15370 | 4720 | 1
MOLECULAR BIOLOGY LAB | REC | 6 | R | 1:00PM | 2:50PM | Rutledge | 16 | 0 | BIOL | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15370 | 4720 | 1
MOLECULAR BIOCHEMISTRY I | LEC | 4 | MR | 10:30AM | 12:35PM | Fraser | 50 | 25 | 25 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15337 | 4760 | 1
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Barquera | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 14909 | 6990 | 1
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Nierzwicki | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 14910 | 6990 | 2
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Ligon | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15175 | 6990 | 4
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Bystroff | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15176 | 6990 | 5
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Bjornsson | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15177 | 6990 | 7
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Hanna | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 14912 | 6990 | 9
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Gilbert | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15178 | 6990 | 10
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Linhardt | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15179 | 6990 | 11
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Rutledge | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15180 | 6990 | 12
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Swank | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15181 | 6990 | 13
MASTER'S THESIS | LEC | 1-9 |   | **TBA** |   | Wang | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15182 | 6990 | 14

`

**Comment by jshom** [comment]
@marchdan sweet! One more thing, can we change **TBA** to Null value in the csv. **TBA** is school specific. 

_**TBA** -> "" (Null String)_

**Comment by marchdan** [comment]
@jshom will do.

**Comment by marchdan** [comment]
Updated parse:

course_name | course_type | course_credit_hours | course_days_of_the_week | course_start_time | course_end_time | course_instructor | course_max_enroll | course_enrolled | course_remained | course_department | course_start_date | course_end_date | semester | course_crn | course_level | course_section
STUDENT SUCCESS LABS | LEC | 0 | W | 1:00PM | 1:50PM | Trzepacz | 120 | 0 | 120 | ADMN | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15486 | 1824 | 1
SUMMER ADMINIST REGISTRATION | LEC | 0 |   |   |   | Grega | 625 | 19 | 606 | ADMN | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 14908 | 6600 | 1
MATERIALS AND DESIGN | LEC | 2 | R | 10:30AM | 12:35PM | Staff | 12 | 2 | 10 | ARCH | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15343 | 2510 | 1
ARCHITECTURAL DESIGN STUDIO 5 | LEC | 5 | MWR | 2:00PM | 5:50PM | Staff | 32 | 32 | 0 | ARCH | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15413 | 4770 | 1
MASTER'S THESIS | LEC | 1-12 |   |   |   | Staff | 10 | 0 | 10 | ARCH | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15031 | 6990 | 3
MASTER'S THESIS | LEC | 1-12 |   |   |   | Staff | 0 | 0 | 0 | ARCH | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15057 | 6990 | 4
ARCHITECTURE DISSERTATION | LEC | 1-15 |   |   |   | Figueiro | 10 | 0 | 10 | ARCH | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15240 | 9990 | 1
ART HISTORY | LEC | 4 | MR | 10:30AM | 12:35PM | Wille Kiel | 60 | 51 | 9 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15371 | 1050 | 1
MUSIC AND TECHNOLOGY 1 | STU | 4 | MR | 8:00AM | 10:05AM | Staff | 19 | 19 | 0 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15688 | 2020 | 1
CHAMBER MUSIC ENSEMBLE |   | 1 | W | 1:30PM | 3:35PM | Staff | 25 | 9 | 16 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15736 | 2350 | 1
PRIVATE MUSIC LESSONS: VIOLIN |   | 1 |   |   |   | Morey/Fisher-Loc | 9 | 1 | 8 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15739 | 2750 | 1
PRIVATE MUSIC LESSONS: VIOLA |   | 1 |   |   |   | Morey/Fisher-Loc | 9 | 0 | 9 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15740 | 2750 | 2
PRIVATE MUSIC LESSONS: FLUTE |   | 1 |   |   |   | Gerbino/Fisher-Loc | 9 | 1 | 8 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15741 | 2750 | 3
PRIVATE MUSIC LESSONS: OBOE |   | 1 |   |   |   | Gerbino/Fisher-Loc | 9 | 0 | 9 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15742 | 2750 | 4
PRIVATE MUSIC LESSONS:CLARINET |   | 1 |   |   |   | Gerbino/Fisher-Loc | 9 | 0 | 9 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15743 | 2750 | 5
PRIVATE MUSIC LESSONS: SAX |   | 1 |   |   |   | Gerbino/Fisher-Loc | 9 | 1 | 8 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15744 | 2750 | 6
PRIVATE MUSIC LESSONS: HARP |   | 1 |   |   |   | Caldicott/Fisher-Loc | 9 | 0 | 9 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15745 | 2750 | 7
PRIVATEMUSICLESSONS:PERCUSSION |   | 1 |   |   |   | Francis/Fisher-Loc | 9 | 2 | 7 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15746 | 2750 | 8
PRIVATE MUSIC LESSONS: VOICE |   | 1 |   |   |   | Harrigan/Fisher-Loc | 9 | 2 | 7 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15747 | 2750 | 9
PRIVATE MUSIC LESSONS: TRUMPET |   | 1 |   |   |   | Williams/Fisher-Loc | 9 | 2 | 7 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15748 | 2750 | 10
GAME SOUND & MUSICAL PLAY | LEC | 4 | MR | 8:00AM | 10:05AM | Galloway | 19 | 13 | 6 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15691 | 2965 | 1
SOUND ECOLOGY | LEC | 4 | MR | 10:30AM | 12:35PM | Galloway | 19 | 1 | 18 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15692 | 2966 | 1
VIDEO ART | STU | 4 | MR | 1:30PM | 3:35PM | Wille Kiel | 16 | 11 | 5 | ARTS | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15693 | 2967 | 1
STARS, GALAXIES AND THE COSMOS | LEC | 4 | MR | 8:00AM | 10:05AM | Martin | 0 | 40 | -40 | ASTR | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15483 | 1960 | 1
EARTH AND SKY | LEC | 4 | TF | 8:00AM | 10:05AM | Martin | 0 | 50 | -50 | ASTR | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15348 | 2120 | 1
MOLECULAR BIOCHEMISTRY I | LEC | 4 | MR | 10:30AM | 12:35PM | Fraser | 50 | 16 | 34 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15338 | 4760 | 1
MASTER'S THESIS | LEC | 1-9 |   |   |   | Wang | 10 | 0 | 10 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15170 | 6990 | 1
DISSERTATION | LEC | 1-15 |   |   |   | Bystroff | 10 | 0 | 10 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15171 | 9990 | 1
DISSERTATION | LEC | 1-15 |   |   |   | Swank | 0 | 0 | 0 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15172 | 9990 | 2
DISSERTATION | LEC | 1-15 |   |   |   | Linhardt | 10 | 0 | 10 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15173 | 9990 | 3
DISSERTATION | LEC | 1-15 |   |   |   | Wang | 10 | 0 | 10 | BCBP | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15174 | 9990 | 4
INTRODUCTION TO CELL BIOLOGY | LEC | 4 | MR | 10:30AM | 12:35PM | Klein | 16 | 1 | 15 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15671 | 2120 | 1
INTRODUCTION TO CELL BIOLOGY | LAB | 4 | T | 12:30AM | 4:30PM | Klein | 1 | 15 | BIOL | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15671 | 2120 | 1
MICROBIOLOGY LABORATORY | LAB | 6 | T | 1:00PM | 5:50PM | Bonocora | 16 | 4 | 12 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15411 | 4320 | 1
MICROBIOLOGY LABORATORY | REC | 6 | R | 1:00PM | 2:50PM | Bonocora | 4 | 12 | BIOL | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15411 | 4320 | 1
MOLECULAR BIOLOGY LAB | LAB | 6 | T | 1:00PM | 5:50PM | Rutledge | 16 | 16 | 0 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15370 | 4720 | 1
MOLECULAR BIOLOGY LAB | REC | 6 | R | 1:00PM | 2:50PM | Rutledge | 16 | 0 | BIOL | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15370 | 4720 | 1
MOLECULAR BIOCHEMISTRY I | LEC | 4 | MR | 10:30AM | 12:35PM | Fraser | 50 | 26 | 24 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15337 | 4760 | 1
MASTER'S THESIS | LEC | 1-9 |   |   |   | Barquera | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 14909 | 6990 | 1
MASTER'S THESIS | LEC | 1-9 |   |   |   | Nierzwicki | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 14910 | 6990 | 2
MASTER'S THESIS | LEC | 1-9 |   |   |   | Ligon | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15175 | 6990 | 4
MASTER'S THESIS | LEC | 1-9 |   |   |   | Bystroff | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15176 | 6990 | 5
MASTER'S THESIS | LEC | 1-9 |   |   |   | Bjornsson | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15177 | 6990 | 7
MASTER'S THESIS | LEC | 1-9 |   |   |   | Hanna | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 14912 | 6990 | 9
MASTER'S THESIS | LEC | 1-9 |   |   |   | Gilbert | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15178 | 6990 | 10
MASTER'S THESIS | LEC | 1-9 |   |   |   | Linhardt | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15179 | 6990 | 11
MASTER'S THESIS | LEC | 1-9 |   |   |   | Rutledge | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15180 | 6990 | 12
MASTER'S THESIS | LEC | 1-9 |   |   |   | Swank | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15181 | 6990 | 13
MASTER'S THESIS | LEC | 1-9 |   |   |   | Wang | 10 | 0 | 10 | BIOL | 2020-05-26 | 2020-08-21 | SUMMER 2020 | 15182 | 6990 | 14
