### ISSUE TITLE
Feature Request — Degree Templates Schema

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#171]
**Job**
Store degree templates

**Describe a possible solution**
Schema file: `12_degree_templates.sql`

New table: `degree_templates`

Columns:
- `primary key`: str           "degree-major-year"
- Degree: str  "B.S"
- Major: str     "CSCI"
- Year: int       2022
- Template: json

JSON Template format:
```
Course {
  type: "Course",
  name: str,
  department: str,
  creditHours: int,
  description?: str,
}

CourseOptions : Course {
  type: "Options",
  options: Course[]
}

Semester {
 courses: (Course|CourseOptions) []
}

Template {
 id: str,
 degree: str,
 major: str,
 year: int,
 semesters: Semester[]
}
```
**Context**

**Comment by DarknessUnder** [comment]
Some change to the schema

Course {
  type: "Course",
  name: str,
  department: str,
  creditHours: int,
  description?: str,
  pre-requsit-of: str
}

Options-Courses : Course {
  creditHours: int
  type: "Options",
  name: str,
  description: str,
  options: Course[]
}

Options-Department : Course {
  creditHours: int
  type: "Options",
  name: str,
  description: str,
  Departments: str[]
}

Semester {
 name: str
 courses: (Course|Options-Courses|Options-Department) []
}

Template {
 id: str,
 degree: str,
 major: str,
 year: int,
 semesters: Semester[]
}

**Comment by 123joshuawu** [comment]
@DarknessUnder Would prefer using camelCase instead of kebab-case

**Comment by 123joshuawu** [comment]
Closing for now to prepare for new semester. Feel free to reopen
