### ISSUE TITLE
Feature Request — Course Explorer - Page for Department/Subject

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#191]
**Job**
When I am looking selecting courses, I want to see all courses offered by a department so that I can see which could fulfill my capstone requirements, or explore which courses are offered within my department/subject. 

**Describe a possible solution**
Department page would show list of courses similar to https://yacs.cs.rpi.edu/courses?subject_id=25 for each subject.

The page should follow the convention `localhost/subject/{{subject_code_lowercase}}` i.e. `localhost/subject/csci` where CSCI is a specific subject.

This page should have generally follow:
```
CSCI
-----
course1 | course2
course3 | course4
... etc
```
and contain the common header.

A back button to return to all subjects/schools page can be handled in another issue when this is complete.

**Context**
Instead of using accordion for departments in Course Explorer, redirect to a new page dedicated for department information.

**Comment by marchdan** [comment]
This looks to have not been closed by PR.
