### ISSUE TITLE
Feature Request — Course Explorer - Page for Course

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#192]
**Job**
Instead of opening a modal when clicking on a course in CourseExplorer, redirect to new page dedicated to the course information

**Describe a possible solution**
New page for course showing various course information:
- links to prerequisite/corequisite courses
- course description
- links to department page
- professor info
- requirement tree? :)
- textbooks
- etc.

**Context**

**Comment by 123joshuawu** [comment]
More ideas:
- tracking occupancy over semesters so we can show if a course ends up full/how full it is at end of registration
- or even tracking occupancy within a semester to see when / how fast it fills up
- show history of course e.g. previous sessions fall 2018, spring 2018
- tags / annotations for courses which can tie into faceted search

**Comment by marchdan** [comment]
> More ideas:
> 
> * tracking occupancy over semesters so we can show if a course ends up full/how full it is at end of registration
> * or even tracking occupancy within a semester to see when / how fast it fills up
> * show history of course e.g. previous sessions fall 2018, spring 2018
> * tags / annotations for courses which can tie into faceted search

@123joshuawu I feel like this has now become relevant again.

**Comment by marchdan** [comment]
> * links to prerequisite/corequisite courses
> * course description
> * links to department page
> * professor info
> * requirement tree? :)
> * textbooks
> * etc.

@123joshuawu Coming back to this:
- The pre/coreq links exist
- Course description exists
- I think having a link to the department page on the department view is still needed
- We have the data on who the professor is for a course, this should be added to the course page
- If we can find a way to link to the courses textbook page on the bookstore website that would be cool
