### ISSUE TITLE
Bug — get_classes_by_search should search all classes when semester is None

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#194]
**Describe the bug**
Noticed this when writing tests for `classinfo`. 

Seems that for `get_classes_by_search`, if `semester` is `None`, it returns `None`

**To Reproduce**
Call `get_classes_by_search(None, None)`

**Expected behavior**
Instead, `get_classes_by_search` should run the query on all classes.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jshom** [comment]
Where does this occur? Maybe worth to throw an exception and not handle this case if it doesn't occur often/in common case. What do you think?

**Comment by 123joshuawu** [comment]
So I don't think this occurs currently..

Our `get_classes` endpoint requires a semester to be provided, thus any calls to `get_classes_by_search` will contain a semester. 

However, I would imagine that being able to list/search classes without providing a semester should be an option, as this functionality could be useful in the course exploration or perhaps admin page. Probably more so the search than the list functionality.
