### ISSUE TITLE
DX — Use page object pattern for cypress tests

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#201]
**Job**
Establish page object pattern for cypress tests

**Describe a possible solution**
https://medium.com/reactbrasil/deep-diving-pageobject-pattern-and-using-it-with-cypress-e60b9d7d0d91

**Context**

**Comment by jshom** [comment]
Lets hold off on this for now

**Comment by 123joshuawu** [comment]
Closing in favor of #230
