### ISSUE TITLE
DX — Upload logs from docker as artifacts if tests fail

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#206]
**Job**
See logs from docker when tests fail

**Describe a possible solution**
Have a step that runs if tests fail that uploads docker logs

**Context**

**Comment by gizzon** [comment]
I can do this one :)

**Comment by jshom** [comment]
@123joshuawu can you add more context here. I assume there was a build where it failed, can you also link to that? thx!

**Comment by 123joshuawu** [comment]
Whoops looks like i got a little ahead of myself. So we currently don't have any tests where we run the containers, but i will update it to do so

**Comment by 123joshuawu** [comment]
Not really useful anymore
