### ISSUE TITLE
Prod - Secure with https

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#208]
**Job**
When I log in, I don't want my password readable in transit.

**Describe a possible solution**
Need HTTPS for production deploy, close http ports and only open 443 for https. Optionally take in certificate, use self-signed cert by default

**Context**
We cannot go to prod without this. Must have.

**Comment by RichtXO** [comment]
Would it be a problem to use a self-signing certificate? This isn't gonna be deployed internally, right?

**Comment by RichtXO** [comment]
Just double-checking, we just need a certificate and have https for the front-end, right?
If so, I don't know if this was necessary, but I made it auto-generate a new certificate when you rerun the prod version. If that's what was needed, I can make a PR of this.
