### ISSUE TITLE
Scheduling - Persist selected courses in cookies

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#210]
**Job**
When I am not logged it, I don't want to lose a schedule I was putting together

**Describe a possible solution**
Cookie a map of selected courses to semesters, so that persisting schedules on the same device does not require logging in.

**Context**
Currently, for someone to see their schedule after a refresh is only through creating an profile, most students will most likely not create an account, so make it easy for them to transition from previous to new yacs.

**Comment by marchdan** [comment]
@RichtXO If you need assistance or have questions on this, let me know. I implemented the course saving system for logged in users.

**Comment by marchdan** [comment]
https://github.com/YACS-RCOS/yacs.n/blob/5036859fb750503981566aa3f4b6dbcece93d493/src/web/src/pages/CourseScheduler.vue#L206-L243

https://github.com/YACS-RCOS/yacs.n/blob/5036859fb750503981566aa3f4b6dbcece93d493/src/web/src/pages/CourseScheduler.vue#L269-L400

This is the current way it is done. If you wanted to implement this, cookies would need to be added where data is stored, and loaded where the data is loaded, as seen above
