### ISSUE TITLE
Scheduling - Schedule Conflict Message

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#211]
**Job**
When I get a schedule conflict, I want to be informed of which courses have conflicts and at what time block so that I can easily find it in the schedule.

**Describe a possible solution**
_Current Message:_
![Screen Shot 2020-10-02 at 3 30 37 PM](https://user-images.githubusercontent.com/11034221/94968893-58d09600-04c7-11eb-8d2c-da89e0d9787d.jpg)

_Change to Message:_
**Header:** Cannot add CONTEMPORARY DESIGN APPROACHES
**Message:** CONTEMPORARY DESIGN APPROACHES [CRN] conflicts with OTHER COURSE [CRN] {color icon} at 10:00AM
_keep color icon the same (the blue box in the screenshot example)_

**Comment by venkatrsrinivas** [comment]
Hello Everyone!
I just was able to work on this Issue, and have been able to implement the Solution as follows:

a[<img width="362" alt="Screen Shot 2020-10-02 at 22 10 37" src="https://user-images.githubusercontent.com/30516782/94980956-3d33b280-04fc-11eb-83ca-11b798be39bd.png">
](url)

**Comment by jshom** [comment]
Awesome!!! 🎊 

Few small tweaks before you finalize:
- Lets remove the "Failure:" prefix, seems a bit harsh word choice for a schedule oopsie :)
- Can you change the time to use [0-12]h AM/PM, we have a moment package you can use to format the time, see https://momentjs.com/docs/#/displaying/
- Also, looking at the message again, repeating the CRN seems a bit redundant in header and message, what do you think about maybe removing the CRN from the header?

**Comment by venkatrsrinivas** [comment]
Hey Jacob!
Thank you for the Prompt Response.
I just made those Quick Changes, so I think everything should be good now.
Let me know what you think, and by the way, I've already made a Pull Request.
