### ISSUE TITLE
UX Bug — Change button color from red to grey

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#221]
**Describe the bug**
Red button here is too alarming for an info popup.

![Screen Shot 2020-10-09 at 1 07 54 PM](https://user-images.githubusercontent.com/11034221/95612615-b0c04d00-0a31-11eb-8d3f-f2969aaca6fb.jpg)

**To Reproduce**
1. Load Spring 2020
2. Find and click on the (i) for CSCI-6360

**Expected behavior**
Change the close button to grey to reduce the amount of attention going to the close button.

**Comment by erinsong** [comment]
gonna start on this one before #68

**Comment by mrpeterli** [comment]
I'll take this issue.

**Comment by jshom** [comment]
closed by #226
