### ISSUE TITLE
UX Bug — Responsive header

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#225]
**Job**
The header should be responsive to screen width

**Describe a possible solution**
Use collapse, toggles, screen size breakpoints to achieve responsiveness
Mainly collapse menu items on smaller screen sizes

**Context**
What it currently looks like on mobile:
![Screen Shot 2020-10-10 at 2 55 14 PM](https://user-images.githubusercontent.com/9285017/95662933-b76dc380-0b08-11eb-8503-d5e0c4d441c6.png)

What is should look like on mobile:
![Screen Shot 2020-10-10 at 2 53 36 PM](https://user-images.githubusercontent.com/9285017/95662936-b89ef080-0b08-11eb-9cea-961094adc459.png)

**Comment by jshom** [comment]
@123joshuawu can you place some screenshots with the key breakpoints, thx!
