### ISSUE TITLE
UX Bug — Course schedule time blocks should not scroll

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#227]
**Job**
Shorter course sessions should not scroll

E.g. The `Student Success Labs` time block has a vertical scroll because its content is greater than its height
![Screen Shot 2020-10-10 at 4 36 48 PM](https://user-images.githubusercontent.com/9285017/95664538-d3786180-0b16-11eb-8c82-c0716d937cfb.png)

**Describe a possible solution**
Hide overflow content (and only show course title?)

**Context**
The schedule time blocks are meant to be a visual representation of one's schedule. All relevant course information is displayed on the left side panel, and users can quickly find them based on the color of each time block. I don't think we need to show the CRN or department and section numbers in the time blocks.

**Comment by marchdan** [comment]
The scroll bars for courses that are too short were added intentionally. They can be removed if wanted, or do we just want them removed for courses less than 2 hours long?

**Comment by 123joshuawu** [comment]
Well I think we don't need to have all that information in the time blocks, at most the title or course number+level should be sufficient in my opinion.

**Comment by marchdan** [comment]
See #70 for the details we added to the blocks.
It was decided to add:
- Course name (Data Strctures)
- CRN (#####)
- Course location (DCC 318)
- Professor(s) (Holzbauer)
- Course number (CSCI-1200)

If crn is displayed elsewhere that might be able to be removed, but the rest were decided as needed for students to view on their schedule.

**Comment by 123joshuawu** [comment]
So a list of CRNs are displayed underneath the schedule grid.
The CRN, course name, course number for each course session is shown in the listing section on the left.

I agree that the information is necessary but I think they are better served shown in the listing section. 

We have the listing block colors match the time block colors so users can find the corresponding sections easily. 

But this probably comes down to a UX/design preference

**Comment by marchdan** [comment]
Yeah, the CRN I agree with, but as a lot of people screenshot it download their schedule, I think the rest of details should be there for people to view when they need. Plus it puts the most relevant details all in one place.

**Comment by marchdan** [comment]
@123joshuawu  While I think schedule blocks should scroll when needed, we should make it so blocks like those shown in the below screenshot don't scroll since they don't need to
![Screenshot 2021-03-10 121828](https://user-images.githubusercontent.com/35609442/110669840-c41b4400-819a-11eb-8b4d-fe488facc5cf.png)
