### ISSUE TITLE
RPI - Spring 2021 Calendar is out

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#237]
**Job**
Have Spring 2021 data in ./rpi_data/

**Describe a possible solution**
Use similar scripts to parse https://sis.rpi.edu/reg/zfs202101.htm

_follow standard in `./rpi_data/` folder_

**Comment by RichtXO** [comment]
Ran script, and running into the problem when parsing. It seems that spring 2021 doesn't have all the information needed. For example, some classes don't have days _yet_. So I'm going to hold this off until RPI releases the days.
