### ISSUE TITLE
UX Bug — User signup modal does not respect dark mode

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#242]
**Describe the bug**
![Screen Shot 2020-10-20 at 4 37 41 PM](https://user-images.githubusercontent.com/9285017/96641521-d59aa700-12f2-11eb-927d-fb677a21e679.png)

**To Reproduce**
1. Toggle dark mode on
2. Click on Sign Up button

**Expected behavior**
Should match rest of site

**Comment by marchdan** [comment]
Also needs to be done for login

**Comment by 123joshuawu** [comment]
@marchdan that aspect was split off to #243

**Comment by marchdan** [comment]
> @marchdan that aspect was split off to #243

Fix should be the same, but I'll work on sign up specifically

**Comment by marchdan** [comment]
The colors for all of the items dealing with the actual b-model are controlled by variant props.

**Comment by marchdan** [comment]
@123joshuawu  thoughts on the issue presented above?

**Comment by 123joshuawu** [comment]
I guess we could explore a custom variant, not really sure how that would work..

The existing precedent would involve overriding the b-modal classes in `dark.scss`, which would fix both login and signup.

If that is the case then we'll just close the other issue as well

**Comment by marchdan** [comment]
@123joshuawu I have tried overriding b-modal, it doesn't seem to take, but I will keep going down that branch

**Comment by 123joshuawu** [comment]
Overriding classes in `dark.scss` do not work right now because the `.dark` class is toggled on the `#root` div. The modal html is injected as a sibling to the `#root` div so the `.dark` class doesn't apply to them. 

#240 contains a fix to this by moving the `.dark` class to `body`

**Comment by marchdan** [comment]
@123joshuawu I will try again later now that #240 has been merged
