### ISSUE TITLE
UX Bug — Brand name impossible to see on hover in dark mode

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#245]
**Describe the bug**
When hovering on brand name in header in dark mode, it turns black

What it looks like without hover:
![Screen Shot 2020-10-20 at 4 35 55 PM](https://user-images.githubusercontent.com/9285017/96642028-8dc84f80-12f3-11eb-80b9-c88c01565227.png)

When it looks like when mouse is hovering over `YACS`
![Screen Shot 2020-10-20 at 4 36 05 PM](https://user-images.githubusercontent.com/9285017/96642027-8d2fb900-12f3-11eb-95d9-a334de17acc4.png)

**To Reproduce**
1. Toggle on dark mode
2. Hover mouse over `YACS` in header

**Expected behavior**
Text should be white but darker variant to indicate that it is being hovered, probably `var(--dark-text-secondary)`

**Comment by marchdan** [comment]
I also noticed that after you click on the name, it stays the same black as it was on hover until you click elsewhere on the page. Please be sure to test that this is fixed when the bug is patched.
