### ISSUE TITLE
UX Bug - Explore Main - Box Shadow

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#259]
**Describe the bug**
Remove the box-shadow in explore main to conform with general styling of the rest of the site

![Screen Shot 2020-10-28 at 7 45 11 PM](https://user-images.githubusercontent.com/11034221/97509139-cd2c1700-1957-11eb-86d1-2ba6e759a9d0.jpg)

**Comment by YuetingLiao** [comment]
@jshom hey Jacob, I removed shadowing lines for Explorer page/ subject page. It will be great if you can tell me the specific requirements.
![eb1be2b0457f466a19a5f2867fa69e0](https://user-images.githubusercontent.com/46305076/97816697-e6d5a300-1c64-11eb-9d4b-efdb7401fa0b.png)
![01de8f41a9678cf3de140f546ab3d63](https://user-images.githubusercontent.com/46305076/97816698-e89f6680-1c64-11eb-8bb7-c97151f1335c.png)
