### ISSUE TITLE
UX Bug - Explore Main - Top Spacing

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#260]
**Describe the bug**
Appears there is little spacing between the beginning of the explore page body and the header, conform to scheduler with what looks like 40px of space between the header and the body

![Screen Shot 2020-10-28 at 7 47 35 PM](https://user-images.githubusercontent.com/11034221/97509219-01073c80-1958-11eb-9905-a5a127cfa4d4.jpg)

**NOTE: Same issue also appears in the department page, please handle as well**

**Comment by 123joshuawu** [comment]
Closed in #270
