### ISSUE TITLE
UX Bug - Explore Department - Drop Box Shadow on Course Listings

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#263]
**Describe the bug**
Course Listings in the department page should drop the box-shadow to conform with site styling.

![Screen Shot 2020-10-28 at 8 09 37 PM](https://user-images.githubusercontent.com/11034221/97510852-06ff1c80-195c-11eb-9209-1395d5602b6c.jpg)

**Additional context**
Depends on https://github.com/YACS-RCOS/yacs.n/issues/262

**Comment by venkatrsrinivas** [comment]
What exactly are we referring to with this Issue?
I'm not sure if this is clear to me.

**Comment by jshom** [comment]
This appears to have already been solved by #291
