### ISSUE TITLE
Bug — Text cut off on mobile

### ISSUE THREAD

**Issue by elihschiff** [YACS-RCOS/yacs.n#271]
**Describe the bug**
On mobile there is text that gets cut off on the left side of the screen

**To Reproduce**
1. https://li1277-238.members.linode.com/explore on mobile
2. see bug

**Expected behavior**
You should be able to see the full text

**Screenshots**
![image](https://user-images.githubusercontent.com/18558130/97762609-79e4d080-1adf-11eb-8f68-75f454b3e6fc.png)

**Comment by jshom** [comment]
Thx for submitting this :+1: @elihschiff, we'll be on it shortly!
