### ISSUE TITLE
Bug — Spring 2021 Data Structures Section 6 has incorrect times

### ISSUE THREAD

**Issue by benjaminrsherman** [YACS-RCOS/yacs.n#273]
**Describe the bug**
The time for Data Structures section 6's lab doesn't match SIS.

**To Reproduce**
Select Data Structures Section 6

**Expected behavior**
It should be the right time.

**Screenshots**
![image](https://user-images.githubusercontent.com/15524035/97764549-5b81d380-1ae5-11eb-946f-8ccd542dc7ed.png)

**Comment by jshom** [comment]
thx! @benjaminrsherman  :+1: we'll be on it asap!

**Comment by jshom** [comment]
![Screen Shot 2020-10-30 at 9 00 46 PM](https://user-images.githubusercontent.com/11034221/97767542-149ada80-1af3-11eb-940f-882a234e2dea.jpg)

Ooof, appears to be coming from the registrar... will email them to update session 6

**Comment by benjaminrsherman** [comment]
> ![Screen Shot 2020-10-30 at 9 00 46 PM](https://user-images.githubusercontent.com/11034221/97767542-149ada80-1af3-11eb-940f-882a234e2dea.jpg)
> 
> Ooof, appears to be coming from the registrar... will email them to update session 6

This is the correct time though - it's 9:05pm to 10:55pm.

**Comment by marchdan** [comment]
This has been patched by #316
