### ISSUE TITLE
Bug — Cannot create an account

### ISSUE THREAD

**Issue by elihschiff** [YACS-RCOS/yacs.n#274]
**Describe the bug**
When I try and create an account I get a "Failed to find user" error

**To Reproduce**
1. click signup
2. fill in the fields
3. click finish
4. see error

**Expected behavior**
I should be able to make an account

**Screenshots**
![image](https://user-images.githubusercontent.com/18558130/97765595-18296400-1ae9-11eb-9a4a-532ba572bb63.png)

**Comment by 123joshuawu** [comment]
Sorry I'm having a little trouble reproducing this. 

It may have been a transient db error, could you try it now and see if it works? @elihschiff 

Thanks!

**Comment by jshom** [comment]
Cannot recreate, appears to have been tied to solved issue with db
