### ISSUE TITLE
Distribution — RPI:Account for course location in data parser

### ISSUE THREAD

**Issue by marchdan** [YACS-RCOS/yacs.n#28]
Need to insert a course location column into the data parse for when course location becomes available

**Comment by jshom** [comment]
No need to worry about this until the locations become available. Watch: https://sis.rpi.edu/reg/zs20200501.htm

**Comment by marchdan** [comment]
Change was made to account for loading Spring 2020, in preparation for Fall 2020. Change just adds a column to table, does not break nor change parsing of current data. Better to account for now, than have to quickly change structure later.
