### ISSUE TITLE
UX Bug — Explore load page spinner offcenter

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#280]
**Describe the bug**
The spinner for the loading pages in explore are off. 
![Screen Shot 2020-10-31 at 1 12 02 AM](https://user-images.githubusercontent.com/9285017/97771726-3d809700-1b16-11eb-8df6-8fccb15b25dd.png)

**To Reproduce**
1. Go to explore
2. Loading screen

**Expected behavior**
These apply to the loading pages for CourseExplorer, SubjectExplorer, and CoursePage
1. The page content should fill 100% page height such that the footer is below the viewport
2. The loading spinner should be in the center of the page

**Comment by kylezehaoqin** [comment]
If we decide to let the spinner div take 100% of window height, users might need to scroll down to see the footer, do we want to have the footer shown with the loading spinner like this?
![image](https://user-images.githubusercontent.com/43757365/98426587-3c87c200-204e-11eb-936f-b8677a822cf0.png)
@jshom
