### ISSUE TITLE
Feature Request — Front End Consistency in Blue 

### ISSUE THREAD

**Issue by charlesv99** [YACS-RCOS/yacs.n#286]
**Job**
The color scheme falls apart throughout the page. Especially in the blue tones that have to do with hyperlinks, buttons, and other links. We should keep consistent with the blue in the current template of the page to keep consistency. Not a major problem but necesarry to say front end is done/close to.

**Context**
Currently working on mockups for a new UI to implement to the page that will better flow of the page and how the user interacts with the page by creating a successful visual hierarchy where the focus will be on the schedule ur creating and added to it instead of splitting it relatively evenly.
![DmSchedulePage](https://user-images.githubusercontent.com/55552005/97794676-7b8fc080-1bd3-11eb-8574-6046d8570037.JPG)

**Comment by jshom** [comment]
thx @charlesv99 for the issue. Can you be more specific about a proposed solution and which elements on the page to change, thx!

**Comment by charlesv99** [comment]
Sorry havent gotten to this. The blue we should match with is #0177ff. the right icons are the right color but the "Schedule" "Explore" &  "Selected Courses/Course Search" are a different shade so the change would be the color of these
