### ISSUE TITLE
Random Spaces In Course Listings

### ISSUE THREAD

**Issue by venkatrsrinivas** [YACS-RCOS/yacs.n#298]
**Description For The Bug**
Hello Everyone.
It seems that there is some extra spacing in the Course Listings for some unknown reason.

**Formal Procedure To Reproduce Bug**
1. Go To Course Listing On YACS
2. Search For RCOS. 

**Expected Behavior**
Condensed Course Listing w/o Random Extra Spaces.
Seems like this is not from the CSV File. 

**Screenshots**
See Below: 
<img width="402" alt="Screen Shot 2020-11-06 at 22 01 12" src="https://user-images.githubusercontent.com/30516782/98430550-2d1f6d80-207c-11eb-87f1-cd1b8780a96c.png">

**Comment by 123joshuawu** [comment]
So starting from the top. 

The API search response for `"rcos"` returns four courses: 
- "RCOS == 1 CREDITS"
- "RCOS == 2 CREDITS"
- "RCOS == 3 CREDITS"
- "RCOS == 4 CREDITS"

So we should be seeing four courses. Instead we only see the four credits course and a lot of empty space..

Jumping into the browser debugger, there's a mysterious `itemsWithSize` computed property in `DynamicScroller` that is a list of four objects
![Screen Shot 2020-11-11 at 8 58 33 PM](https://user-images.githubusercontent.com/9285017/98885804-b0680700-2460-11eb-842b-2c5f69eaf595.png)

Apparently this is how the scroller keeps track of the size of each element? https://github.com/Akryum/vue-virtual-scroller/issues/307#issuecomment-554611148

Opening them up, we can see that all four objects seem to correspond to the RCOS course and they all have the same id
![Screen Shot 2020-11-11 at 9 00 26 PM](https://user-images.githubusercontent.com/9285017/98886024-28363180-2461-11eb-90d6-040eb9d5a66b.png)

From the docs https://github.com/Akryum/vue-virtual-scroller
> ⚠️ If the items are objects, the scroller needs to be able to identify them. By default it will look for an id field on the items. This can be configured with the keyField prop if you are using another field name.

If we open up the objects, we'll actually see that each entry is a different object, but they all have the same id. So where are the ids created?

This is actually synthesized in `YacsService` by this function:
https://github.com/YACS-RCOS/yacs.n/blob/5036859fb750503981566aa3f4b6dbcece93d493/src/web/src/services/YacsService.js#L16-L33

Hint: Notice anything missing from the id creation?

**Comment by venkatrsrinivas** [comment]
Oh I see exactly what you mean, Josh.
The Title + Name For Course Are Missing.
Technically, Title alone should be sufficient, but I also added Name just to be safe.
That was a pretty simple fix.
