### ISSUE TITLE
Feature Request — Prerequisites should say whether they're an OR or an AND

### ISSUE THREAD

**Issue by benjaminrsherman** [YACS-RCOS/yacs.n#302]
**Job**
Right now, when a course has multiple prerequisites they are just displayed with a comma between them.  For some classes, you must have all of the prerequisites (e.g. Xinformatics requires CSCI 1200 and CSCI 4350).  For others, you can have any of the prerequisites (e.g. Computability and Logic requires PHIL 2140 or CSCI 2200), and for some there is a combination (e.g. Operating Systems requires CSCI 2300 and either CSCI 2500 or ECSE 2660).  The current approach makes it impossible to tell which combinations of the prerequisites are actually required, rendering the list of them almost useless.

**Describe a possible solution**
Instead of saying "Requires completion of X, Y, Z", YACS should say something like "Requires completion of X and Y or Z".

**Comment by IkeLyons** [comment]
Closed by pull request #323
