### ISSUE TITLE
Inconsistent Course Time Data

### ISSUE THREAD

**Issue by venkatrsrinivas** [YACS-RCOS/yacs.n#303]
**Description For The Bug**
Hello Everyone.
It seems that there are some Incorrect Course Times for Industrial + Organization Psychology.
I'm not sure if this is the case with other Courses as well, but I noticed this while Scheduling. 

**Formal Procedure To Reproduce Bug**
1. Go To Course Listing On YACS.
2. Search For Industrial + Organization Psychology + Confirm Time Is Incorrectly 8:00 AM - 9:50 AM.

**Expected Behavior**
Consistent Times w/ SIS Website. 

**Screenshots**
The Actual Data, Presented On YACS: 
<img width="399" alt="Screen Shot 2020-11-09 at 19 27 15" src="https://user-images.githubusercontent.com/30516782/98612464-37cb4400-22c2-11eb-9814-f77cbcc92902.png">

The Expected Data From SIS Website:
<img width="1280" alt="Screen Shot 2020-11-09 at 19 27 22" src="https://user-images.githubusercontent.com/30516782/98612501-487bba00-22c2-11eb-85f6-46615ddb8888.png">

**Comment by jshom** [comment]
Fixed, update spring semester. Will add pr in a sec with updated csv
