### ISSUE TITLE
Bug — Save course selection duplicate key error

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#307]
**Describe the bug**
Seeing this issue in the logs

```
yacs_db     | 2020-11-08 20:45:29.081 UTC [30] ERROR:  duplicate key value violates unique constraint "student_course_selection_pkey"
yacs_db     | 2020-11-08 20:45:29.081 UTC [30] DETAIL:  Key (user_id, semester, course_name, crn)=(14, SPRING 2021, MANE-4040, -1) already exists.
yacs_db     | 2020-11-08 20:45:29.081 UTC [30] STATEMENT:
yacs_db     | 					INSERT INTO
yacs_db     | 						student_course_selection (user_id, semester, course_name, crn)
yacs_db     | 					VALUES
yacs_db     | 						('14', 'SPRING 2021', 'MANE-4040', '-1')
```

**To Reproduce**
Not sure how to reproduce yet, my guess is it is when people are logged in, add a class, remove it, then do something else with it.

**Goal**
Find way to reproduce and solve the issue with error catching and proper UI message

**Comment by marchdan** [comment]
Something is happening where you're trying to add a course from the course search tab but it already exists in the db. I can't seem to recreate, but I'm also not sure how that could happen unless we have 2 people with the user is '14'
