### ISSUE TITLE
Bug — Incorrect Class Time for ECSE-2050

### ISSUE THREAD

**Issue by Longshotrider** [YACS-RCOS/yacs.n#309]
**Describe the bug**
ECSE-2050 has incorrect class time recorded, with the 8:00 pm time slot for Tuesday replaced with 8:00 am. 

**To Reproduce**
1. Go to the main page for the Spring 2021 semester.
2. Pull up the ECSE-2050 course.

**Expected behavior**
Time on Tuesday should be from 8:00 pm to 9:50 pm, rather than from 8:00 am to 9:50 pm. 

**Screenshots**
![image](https://user-images.githubusercontent.com/50577211/98817567-4582e580-23f8-11eb-8a8c-b27a95ac6db1.png)
![image](https://user-images.githubusercontent.com/50577211/98817632-621f1d80-23f8-11eb-8e67-ddfb3f55772d.png)

**Additional context**
EDIT: Further investigation reveals that it happens with any class with an 8:00pm class start time.

**Comment by marchdan** [comment]
@Longshotrider there is a good chance that this issue happens with all 8am classes. If so, it's a parser error that I can fix. Please check and lmk

**Comment by Longshotrider** [comment]
I looked further into it, and it seems to happen with classes that have a starting time of 8:00 pm. Swapping the start time to 8:00 am.

**Comment by marchdan** [comment]
Yeah, that would happen because we've never had classes with that late a start time. I can look at the data and make the patch in the parser.

**Comment by jshom** [comment]
For now changed it in the db @Longshotrider, sorry for the inconvenience.
![Screen Shot 2020-11-11 at 12 10 31 PM](https://user-images.githubusercontent.com/11034221/98841991-e6809900-2416-11eb-99cd-bffe954089c9.jpg)

**Comment by marchdan** [comment]
@jshom Yep, I am fixing it now
