### ISSUE TITLE
Scheduling — Schedule Rendering Issue

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#31]
![Screen Shot 2020-03-06 at 1 19 50 PM](https://user-images.githubusercontent.com/11034221/76110939-66fc1980-5fad-11ea-83f1-daf38b95ad97.jpg)

8AM should be at 8AM, appears to be shifted down by a bit

**Comment by 123joshuawu** [comment]
Ok I was displaying the wrong times in the selected courses... I forgot to include the minutes
