### ISSUE TITLE
Bug — class API returns null sections

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#317]
**Describe the bug**
The class API returns courses with sections that are literally `null`

For the example below, the course ADMN-1030 sections should be an empty list 
![Screen Shot 2020-11-11 at 2 24 36 PM](https://user-images.githubusercontent.com/9285017/98855350-daea9d80-2429-11eb-9c1f-7ebec39ece87.png)

**To Reproduce**
1. GET https://yacs.cs.rpi.edu/api/class?semester=SPRING%202021
2. check sections of first course listed

**Expected behavior**
List of sections should not contain `null` values

**Comment by JuliaShiweiHuang** [comment]
doing `return json.dumps(data, default=str).replace("null", "")` will remove the null but unfortunately breaks json template. I am working around the issue.
