### ISSUE TITLE
Bug — Number of seats in csv are not accurate

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#318]
**Describe the bug**
The columns `course_enrolled` and `course_remained` are not accurate.

It looks like `course_enrolled` is always 0 and `course_remained` is either 0 or equal to `course_max_enroll`

E.g Notice the below courses (pulled from spring 2021 csv)
```
ENVIRONMENTAL AND ECOL SYSTEM,LEC,4,MR,8:00AM,9:50AM,Lokko,,80,0,80,ARCH,2021-01-18,2021-05-07,SPRING 2021,40359,2360,01,ARCH-2360,Environmental and Ecological Systems,"An exploration of the fundamental principles of human physiology, thermal and luminous comfort, and indoor quality. Emphasis is on bioclimatic and psychrometric climate analysis and its relationship to architectural design, understanding the energy exchange between body in space, the natural meaning of enclosures, and nonstructural materials and systems. The focus is on passive heating, cooling, and daylighting systems and their design. Exercises include vital sign analysis of existing spaces (thermal, air, luminous), forming hypotheses of building performance, using scientific instrumentation, tenant survey techniques, and physical modeling and simulation techniques related to daylighting and shading techniques.","Prerequisites: ARCH 2370 Energy, Comfort and Ecology. Corequisites: PHYS 1500, ARCH 2830.",Spring term annually.,['ARCH-2370'],"['PHYS-1500', 'ARCH-2830']",Architecture
"ENERGY, COMFORT & ECOLOGY",LEC,2,W,10:10AM,12:00PM,Loercher,,70,0,70,ARCH,2021-01-18,2021-05-07,SPRING 2021,42775,2370,01,ARCH-2370,"Energy, Comfort, and Ecology","This course addresses fundamental principles relating the environmental context to human needs and comfort. Topics include the principles of thermodynamics at the architectural scale, optimization versus variability, principles of building sites and orientations, psychometrics, and human comfort, and an introduction to energy modeling. This course is required of all students in the B.Arch. degree program.",,Spring term annually.,[],[],Architecture
DIGITAL CONSTRUCTS 2,LEC,2,,,,Dayem,,40,0,40,ARCH,2021-01-18,2021-05-07,SPRING 2021,42779,2530,01,ARCH-2530,Digital Constructs 2,This course builds upon topics covered in Digital Constructs 1 by focusing upon contemporary means of producing and communicating architectural ideas. Students will use digital methodologies through all phases of a project as well as advanced representation and digital fabrication techniques. The use of digital modeling as a sketch and iterative tool will be emphasized. Tools taught in Digital Constructs 2 will build upon those software programs taught in Digital Constructs 1. This course is required of all first-year architecture undergraduates in the B.Arch. program. Coordination of the relationship of course content to Architectural Design Studio 2 will be between the Digital Constructs 2 faculty instructor and the first-year architectural design studio coordinator and faculty.,Prerequisite: ARCH 2520 Digital Constructs 1. Corequisites: ARCH 2810 Architectural Design Studio 2.,Spring term annually.,['ARCH-2520'],['ARCH-2810'],Architecture
DIGITAL CONSTRUCTS 2,LEC,2,,,,Liu,,40,0,40,ARCH,2021-01-18,2021-05-07,SPRING 2021,44852,2530,02,ARCH-2530,Digital Constructs 2,This course builds upon topics covered in Digital Constructs 1 by focusing upon contemporary means of producing and communicating architectural ideas. Students will use digital methodologies through all phases of a project as well as advanced representation and digital fabrication techniques. The use of digital modeling as a sketch and iterative tool will be emphasized. Tools taught in Digital Constructs 2 will build upon those software programs taught in Digital Constructs 1. This course is required of all first-year architecture undergraduates in the B.Arch. program. Coordination of the relationship of course content to Architectural Design Studio 2 will be between the Digital Constructs 2 faculty instructor and the first-year architectural design studio coordinator and faculty.,Prerequisite: ARCH 2520 Digital Constructs 1. Corequisites: ARCH 2810 Architectural Design Studio 2.,Spring term annually.,['ARCH-2520'],['ARCH-2810'],Architecture
DIGITAL CONSTRUCTS 4,LEC,2,,,,Imaeda,,40,0,40,ARCH,2021-01-18,2021-05-07,SPRING 2021,43178,2550,01,ARCH-2550,Digital Constructs 4,"Building on techniques taught in Digital Constructs 3, this course will expand upon the role of technology in architecture by introducing advanced methods of design analysis and resolution. Students will learn to address issues of optimization, environmental surroundings, structure, and site by using various contemporary analytic software programs. This course is offered in the spring semester and is required of all second-year architecture undergraduates in the B.Arch. program. Coordination of the relationship of course content to Architectural Design Studio 4 will be between the Digital Constructs 4 faculty instructor and the second-year architectural design studio coordinator and faculty.",Prerequisite: ARCH 2540 Digital Constructs 3; corequisite: ARCH 2830 Architectural Design 4.,Spring term annually.,['ARCH-2540'],['ARCH-2830'],Architecture
DIGITAL CONSTRUCTS 4,LEC,2,,,,Lopez,,40,0,40,ARCH,2021-01-18,2021-05-07,SPRING 2021,44522,2550,02,ARCH-2550,Digital Constructs 4,"Building on techniques taught in Digital Constructs 3, this course will expand upon the role of technology in architecture by introducing advanced methods of design analysis and resolution. Students will learn to address issues of optimization, environmental surroundings, structure, and site by using various contemporary analytic software programs. This course is offered in the spring semester and is required of all second-year architecture undergraduates in the B.Arch. program. Coordination of the relationship of course content to Architectural Design Studio 4 will be between the Digital Constructs 4 faculty instructor and the second-year architectural design studio coordinator and faculty.",Prerequisite: ARCH 2540 Digital Constructs 3; corequisite: ARCH 2830 Architectural Design 4.,Spring term annually.,['ARCH-2540'],['ARCH-2830'],Architecture
```

And on sis https://sis.rpi.edu/reg/zfs202101.htm:
![Screen Shot 2020-11-11 at 3 13 37 PM](https://user-images.githubusercontent.com/9285017/98859718-96aecb80-2430-11eb-8cbf-6bc6b43291f7.png)

**To Reproduce**
1. Compare spring 2021 csv with sis

**Comment by marchdan** [comment]
I can patch once #316 is merged

**Comment by marchdan** [comment]
`
DIGITAL CONSTRUCTS 2 | LEC | 2 |   |   |   | Dayem |   | 40 | 5 | 35 | ARCH | 2021-01-18 | 2021-05-07 | SPRING 2021 | 42779 | 2530 | 1 | ARCH-2530 | Digital Constructs 2 | This course builds upon topics covered in Digital Constructs 1 by focusing upon contemporary means of producing and communicating architectural ideas. Students will use digital methodologies through all phases of a project as well as advanced representation and digital fabrication techniques. The use of digital modeling as a sketch and iterative tool will be emphasized. Tools taught in Digital Constructs 2 will build upon those software programs taught in Digital Constructs 1. This course is required of all first-year architecture undergraduates in the B.Arch. program. Coordination of the relationship of course content to Architectural Design Studio 2 will be between the Digital Constructs 2 faculty instructor and the first-year architectural design studio coordinator and faculty. | Prerequisite: ARCH 2520 Digital Constructs 1. Corequisites: ARCH 2810 Architectural Design Studio 2. | Spring term annually. | ['ARCH-2520'] | ['ARCH-2810'] | Architecture
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DIGITAL CONSTRUCTS 2 | LEC | 2 |   |   |   | Liu |   | 40 | 1 | 39 | ARCH | 2021-01-18 | 2021-05-07 | SPRING 2021 | 44852 | 2530 | 2 | ARCH-2530 | Digital Constructs 2 | This course builds upon topics covered in Digital Constructs 1 by focusing upon contemporary means of producing and communicating architectural ideas. Students will use digital methodologies through all phases of a project as well as advanced representation and digital fabrication techniques. The use of digital modeling as a sketch and iterative tool will be emphasized. Tools taught in Digital Constructs 2 will build upon those software programs taught in Digital Constructs 1. This course is required of all first-year architecture undergraduates in the B.Arch. program. Coordination of the relationship of course content to Architectural Design Studio 2 will be between the Digital Constructs 2 faculty instructor and the first-year architectural design studio coordinator and faculty. | Prerequisite: ARCH 2520 Digital Constructs 1. Corequisites: ARCH 2810 Architectural Design Studio 2. | Spring term annually. | ['ARCH-2520'] | ['ARCH-2810'] | Architecture
DIGITAL CONSTRUCTS 4 | LEC | 2 |   |   |   | Imaeda |   | 40 | 2 | 38 | ARCH | 2021-01-18 | 2021-05-07 | SPRING 2021 | 43178 | 2550 | 1 | ARCH-2550 | Digital Constructs 4 | Building on techniques taught in Digital Constructs 3, this course will expand upon the role of technology in architecture by introducing advanced methods of design analysis and resolution. Students will learn to address issues of optimization, environmental surroundings, structure, and site by using various contemporary analytic software programs. This course is offered in the spring semester and is required of all second-year architecture undergraduates in the B.Arch. program. Coordination of the relationship of course content to Architectural Design Studio 4 will be between the Digital Constructs 4 faculty instructor and the second-year architectural design studio coordinator and faculty. | Prerequisite: ARCH 2540 Digital Constructs 3; corequisite: ARCH 2830 Architectural Design 4. | Spring term annually. | ['ARCH-2540'] | ['ARCH-2830'] | Architecture
DIGITAL CONSTRUCTS 4 | LEC | 2 |   |   |   | Lopez |   | 40 | 0 | 40 | ARCH | 2021-01-18 | 2021-05-07 | SPRING 2021 | 44522 | 2550 | 2 | ARCH-2550 | Digital Constructs 4 | Building on techniques taught in Digital Constructs 3, this course will expand upon the role of technology in architecture by introducing advanced methods of design analysis and resolution. Students will learn to address issues of optimization, environmental surroundings, structure, and site by using various contemporary analytic software programs. This course is offered in the spring semester and is required of all second-year architecture undergraduates in the B.Arch. program. Coordination of the relationship of course content to Architectural Design Studio 4 will be between the Digital Constructs 4 faculty instructor and the second-year architectural design studio coordinator and faculty. | Prerequisite: ARCH 2540 Digital Constructs 3; corequisite: ARCH 2830 Architectural Design 4. | Spring term annually. | ['ARCH-2540'] | ['ARCH-2830'] | Architecture


`

**Comment by marchdan** [comment]
SPRING 2021 | 42779 | 2530 | 1 | ARCH-2530 | Digital Constructs 2
-- | -- | -- | -- | -- | --
SPRING 2021 | 44852 | 2530 | 2 | ARCH-2530 | Digital Constructs 2
SPRING 2021 | 43178 | 2550 | 1 | ARCH-2550 | Digital Constructs 4
SPRING 2021 | 44522 | 2550 | 2 | ARCH-2550 | Digital Constructs 4

**Comment by marchdan** [comment]
Looks ok to me:
`

DIGITAL CONSTRUCTS 2 | LEC | 2 |   |   |   | Dayem |   | 40 | 5 | 35
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DIGITAL CONSTRUCTS 2 | LEC | 2 |   |   |   | Liu |   | 40 | 1 | 39
DIGITAL CONSTRUCTS 4 | LEC | 2 |   |   |   | Imaeda |   | 40 | 2 | 38
DIGITAL CONSTRUCTS 4 | LEC | 2 |   |   |   | Lopez |   | 40 | 0 | 40



`

**Comment by marchdan** [comment]
Those last 3 columns are the enrollment columns from my local csv

**Comment by marchdan** [comment]
@123joshuawu Is that what you're looking for?

**Comment by 123joshuawu** [comment]
Oh is my csv out of date?

**Comment by marchdan** [comment]
Yes. Registration has started so the SIS site will be changing every 15 minutes XD

**Comment by marchdan** [comment]
The csv in #316 is accurate them

**Comment by 123joshuawu** [comment]
Sounds godo ill close
