### ISSUE TITLE
Feature Request — Add button to export schedule grid as an image

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#329]
**Job**
Currently we allow users to export schedules in ics format and the expectation for images is that they can screenshot it. But it would be helpful if we provide an option for users to export the schedule as an image

**Describe a possible solution**
Another button next to `export as ics` with `export as image` that exports the schedule grid as an image
Or change that button to a dropdown menu

**Context**

**Comment by venkatrsrinivas** [comment]
Anyone have any advice on how we ought to approach the Exxportation of the Schedule as an Image? 
I've been trying to use the Vue-HTML2ToCanvas Library to attempt to "screenshot" the Schedule Component, but it's really not working. 
I was wondering if anyone had any input. 
I've already implemented the Drop-Down Functionality, just need to figure out the Main Image Part.

**Comment by marchdan** [comment]
@venkatrsrinivas Here is the implementation from old YACS:
```
public downloadImage (): void {
      var node = this.scheduleNode;

      domtoimage.toPng(node, { bgcolor:"white", quality: 1.0 })
        .then(function (dataUrl) {
            var link = document.createElement('a');
            link.download = 'mySchedules.png';
            link.href = dataUrl;
            link.click();
        })
        .catch(function(error) {
          console.error('oops, something went wrong!', error);
        });
  }
```

**Comment by venkatrsrinivas** [comment]
Hey Dan.
Thank you for this!
I'm going to see if I can similarly implement this DOM Node Structure in the New YACS.

**Comment by venkatrsrinivas** [comment]
Update: I think I have it working. I'll do some Testing, Documentation, and then make a Pull Request soon. 
Thank you Dan and Josh for all of the help!
