### ISSUE TITLE
Feature Request — Readdition of previous YACS features in the future?

### ISSUE THREAD

**Issue by PMARC14** [YACS-RCOS/yacs.n#332]
**Job**
Course permutate option, course shortlist that can be toggled.

**Describe a possible solution**
I am not sure what happened to these features, if there was a conflict with the update, but I would like to see them re-added

**Context**
In the new YACS update, while the UI was greatly improved, we lost some very useful features. Biggest one was the course permutation arrows that allowed me to look at all the combinations of currently selected courses I could take. This is very useful when planning out a schedule or choosing a lab slot, as selecting the courses one by one is tedious and slow. Similarly I am now unable to add bunch of courses and turn a respective one off to compare schedules, which also slows the course comparison process. If I have a course added, I have to remove it and then add another course which is much more tedious

**Comment by marchdan** [comment]
With this should also come one of two things. 

1. Auto-generation of all possible schedules (Old Yacs)
2. Limit that you can only have one section of a course on your schedule at once
     So you can only click on course sections that will fit our current schedule, and when you select a section it removes the one that was previously selected

**Comment by jshom** [comment]
Thx for reporting the issue! We'll make sure to take care of this.

**Comment by 123joshuawu** [comment]
@marchdan We can do 2. pretty easily, though I think when we were making it we decided to allow multiple sections per course? If I recall correctly, it was for TAs specifically. Maybe we add like an advanced settings page with an option to toggle allowing multiple sections?

**Comment by marchdan** [comment]
@123joshuawu I think that is a smart idea. I'm thinking of the majority of our users who just care about which one section they need to enroll in. 

Also, along with this, we need to be sure it includes the functionality to attempt to switch sections around if the user selects a course which doesn't have any section that can fit on the exact schedule being displayed 

We just need to keep in mind that option 1 conforms to the submitted issue and the old yacs model . While option 2, I feel, conforms more to the direction I feel like we have been going.
