### ISSUE TITLE
Bug — Course explorer navigation to nonexistent courses

### ISSUE THREAD

**Issue by marchdan** [YACS-RCOS/yacs.n#344]
**Describe the bug**
When using the course explorer to look at a course, it provides links to all of a courses prereqs, even if the prereq course is not in our database

**To Reproduce**
1. Load the yacs environment and SPRING 2021
2. Navigate to explore -> CSCI -> CSCI-220
3. Click on the MATH-1500 prereq
4. Notice how the page hangs on the course load screen forever

**Expected behavior**
There should not be a link available for courses that do not have a page in the explorer.

**Comment by RichtXO** [comment]
This seems to be fixed!
