### ISSUE TITLE
Feature Request — 404 page for non matching routes

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#346]
**Job**
When user tries to go to a route that does not exist, we should show a 404 Page Not Found error page

**Describe a possible solution**
Have a default route that shows 404 page

**Context**

**Comment by 123joshuawu** [comment]
After this is complete, we should put in 404 for the explore feature. e.g. https://yacs.cs.rpi.edu/explore/alksdfjaldksf and https://yacs.cs.rpi.edu/explore/ARTS/alksdfjaldksf

**Comment by marchdan** [comment]
Linking this to #344

**Comment by marchdan** [comment]
> After this is complete, we should put in 404 for the explore feature. e.g. https://yacs.cs.rpi.edu/explore/alksdfjaldksf and https://yacs.cs.rpi.edu/explore/ARTS/alksdfjaldksf

Linking this to #344

**Comment by marchdan** [comment]
Yet Another 404 Error

**Comment by 123joshuawu** [comment]
Throwback to where it all began for me lol :D https://github.com/YACS-RCOS/yacs/pull/509

**Comment by marchdan** [comment]
I feel like we only have one option: https://github.com/YACS-RCOS/yacs/pull/490
