### ISSUE TITLE
Bug — Digital Constructs Spring 2021

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#363]
**Describe the bug**
The course Digital Constructs in Spring 2021 has no course start time or end time but has a day of the week. 

**To Reproduce**
1. Go to course scheduling page
2. Add Digital Constructs

**Expected behavior**
The course should not have a day of the week. 

**Screenshots**
On SIS, it indicates that the course time is TBA
![Screen Shot 2020-11-27 at 12 44 10 AM](https://user-images.githubusercontent.com/9285017/100415342-ed7bee00-3049-11eb-95f7-839423aa53fd.png)

However in the database it has a course day of 2
![Screen Shot 2020-11-27 at 12 45 43 AM](https://user-images.githubusercontent.com/9285017/100415340-ec4ac100-3049-11eb-8bd2-73017fb65ab2.png)

And then in the application this happens
![Screen Shot 2020-11-27 at 12 44 27 AM](https://user-images.githubusercontent.com/9285017/100415341-ece35780-3049-11eb-8b9f-27532d866c5d.png)

**Comment by marchdan** [comment]
@123joshuawu this much be a backend issue, here is the view from the CSV:


course_name | course_type | course_credit_hours | course_days_of_the_week | course_start_time | course_end_time | course_instructor | course_location | course_max_enroll | course_enrolled | course_remained | course_department | course_start_date | course_end_date | semester | course_crn | course_level | course_section | short_name | full_name | description | raw_precoreqs | offer_frequency | prerequisites | corequisites | school
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DIGITAL CONSTRUCTS   2 | LEC | 2 |   |   |   | Dayem |   | 40 | 39 | 1 | ARCH | ######## | 5/7/2021 | SPRING 2021 | 42779 | 2530 | 1 | ARCH-2530 | Digital Constructs 2 | This course builds upon topics covered in   Digital Constructs 1 by focusing upon contemporary means of producing and   communicating architectural ideas. Students will use digital methodologies   through all phases of a project as well as advanced representation and   digital fabrication techniques. The use of digital modeling as a sketch and   iterative tool will be emphasized. Tools taught in Digital Constructs 2 will   build upon those software programs taught in Digital Constructs 1. This   course is required of all first-year architecture undergraduates in the   B.Arch. program. Coordination of the relationship of course content to   Architectural Design Studio 2 will be between the Digital Constructs 2   faculty instructor and the first-year architectural design studio coordinator   and faculty. | Prerequisite: ARCH 2520 Digital Constructs 1.   Corequisites: ARCH 2810 Architectural Design Studio 2. | Spring term annually. | ['ARCH-2520'] | ['ARCH-2810'] | Architecture
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DIGITAL CONSTRUCTS 2 | LEC | 2 |   |   |   | Liu |   | 40 | 15 | 25 | ARCH | ######## | 5/7/2021 | SPRING 2021 | 44852 | 2530 | 2 | ARCH-2530 | Digital Constructs 2 | This course builds upon topics covered in Digital Constructs 1 by   focusing upon contemporary means of producing and communicating architectural   ideas. Students will use digital methodologies through all phases of a   project as well as advanced representation and digital fabrication   techniques. The use of digital modeling as a sketch and iterative tool will   be emphasized. Tools taught in Digital Constructs 2 will build upon those   software programs taught in Digital Constructs 1. This course is required of   all first-year architecture undergraduates in the B.Arch. program.   Coordination of the relationship of course content to Architectural Design   Studio 2 will be between the Digital Constructs 2 faculty instructor and the   first-year architectural design studio coordinator and faculty. | Prerequisite: ARCH 2520 Digital Constructs 1. Corequisites: ARCH 2810   Architectural Design Studio 2. | Spring term annually. | ['ARCH-2520'] | ['ARCH-2810'] | Architecture
DIGITAL CONSTRUCTS 4 | LEC | 2 |   |   |   | Imaeda |   | 40 | 40 | 0 | ARCH | ######## | 5/7/2021 | SPRING 2021 | 43178 | 2550 | 1 | ARCH-2550 | Digital Constructs 4 | Building on techniques taught in Digital Constructs 3, this course will   expand upon the role of technology in architecture by introducing advanced   methods of design analysis and resolution. Students will learn to address   issues of optimization, environmental surroundings, structure, and site by   using various contemporary analytic software programs. This course is offered   in the spring semester and is required of all second-year architecture   undergraduates in the B.Arch. program. Coordination of the relationship of   course content to Architectural Design Studio 4 will be between the Digital   Constructs 4 faculty instructor and the second-year architectural design   studio coordinator and faculty. | Prerequisite: ARCH 2540 Digital Constructs 3; corequisite: ARCH 2830   Architectural Design 4. | Spring term annually. | ['ARCH-2540'] | ['ARCH-2830'] | Architecture
DIGITAL CONSTRUCTS 4 | LEC | 2 |   |   |   | Lopez |   | 40 | 22 | 18 | ARCH | ######## | 5/7/2021 | SPRING 2021 | 44522 | 2550 | 2 | ARCH-2550 | Digital Constructs 4 | Building on techniques taught in Digital Constructs 3, this course will   expand upon the role of technology in architecture by introducing advanced   methods of design analysis and resolution. Students will learn to address   issues of optimization, environmental surroundings, structure, and site by   using various contemporary analytic software programs. This course is offered   in the spring semester and is required of all second-year architecture   undergraduates in the B.Arch. program. Coordination of the relationship of   course content to Architectural Design Studio 4 will be between the Digital   Constructs 4 faculty instructor and the second-year architectural design   studio coordinator and faculty. | Prerequisite: ARCH 2540 Digital Constructs 3; corequisite: ARCH 2830   Architectural Design 4. | Spring term annually. | ['ARCH-2540'] | ['ARCH-2830'] | Architecture

**Comment by marchdan** [comment]
@123joshuawu this much be a backend issue, here is the view from the CSV:


course_credit_hours | course_days_of_the_week | course_start_time | course_end_time | course_instructor | course_location | course_max_enroll | course_enrolled | course_remained | course_department | course_start_date | course_end_date | semester
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --




DIGITAL CONSTRUCTS   2 | LEC | 2 |   |   |   | Dayem |   | 40 | 39 | 1 | ARCH | ######## | 5/7/2021 | SPRING 2021
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DIGITAL CONSTRUCTS 2 | LEC | 2 |   |   |   | Liu |   | 40 | 15 | 25 | ARCH | ######## | 5/7/2021 | SPRING 2021
DIGITAL CONSTRUCTS 4 | LEC | 2 |   |   |   | Imaeda |   | 40 | 40 | 0 | ARCH | ######## | 5/7/2021 | SPRING 2021
DIGITAL CONSTRUCTS 4 | LEC | 2 |   |   |   | Lopez |   | 40 | 22 | 18 | ARCH | ######## | 5/7/2021 | SPRING 2021
