### ISSUE TITLE
Feature Request — Department Explore Page, One -> Two Columns

### ISSUE THREAD

**Issue by nick-lennox** [YACS-RCOS/yacs.n#367]
**Describe the bug**
Not necessarily a bug, but every department is in one giant column on the explore page. I think it may be beneficial to split it up into two separate columns so the user doesn't have to do as much scrolling. It seems like everything should be able to fit onto the page for mobile platforms.

**To Reproduce**
1. check out explore page on mobile UI
2. do a lot of scrolling to get to the bottom

**Expected behavior**
Two columns instead of one on that page

**Screenshots**
![ezgif-7-3ac8d036b574](https://user-images.githubusercontent.com/44211696/100950893-6b714680-34db-11eb-9094-5bea51f42e4b.gif)

**Comment by marchdan** [comment]
@nick-lennox I believe this behavior is because the columns would overlap or text would be too small if the page was in two columns at that size.
