### ISSUE TITLE
Feature Request — Hidden Footer

### ISSUE THREAD

**Issue by charlesv99** [YACS-RCOS/yacs.n#370]
![12-06](https://user-images.githubusercontent.com/55552005/101304317-ffaa1900-380d-11eb-9224-bd54343a8150.JPG)
On the Landing page there is a lot going on, I feel its a little overwhelming and was thinking the footer at the bottom of each page could be hidden until an event, being scrolling extra or a secondary time after reaching the bottom of the frame. Commonly seen in Phone apps.

**Comment by 123joshuawu** [comment]
Probaby setting min height of container to 100vh would do the trick? would have to set that only for desktop though
