### ISSUE TITLE
Feature Request — Improve Text Hierarchy and styling

### ISSUE THREAD

**Issue by charlesv99** [YACS-RCOS/yacs.n#372]
The text hierarchy on the landing page is all over the place. the CRN under class selection are significantly bolder and larger than all other text on screen and take attention away from the primary focus on the screen which should be the schedule grid.

The Left container being the selected courses and class selection should be uniform in font and text boldness where we only have a couple differentiations in boldness. for Example:
1- Title
2- Search & Filter Titles, CRNs of classes
3- everything else
this is a good visual hierarchy for the left most container.

The YACS Logo should also be the boldest text on the page and the rest of the nav bar should follow and maybe match similarly to the second level of the left containers hierarchy.

The footer should be the lightest text and should be hidden as mentioned in the previous feature request. the footer should mathc the boldness of last level of the left containers hierarchy.
 Also A box or shade of grey should differentiate the different containers in a slight way especially for the course list under class selection where the space to click for each course is very vague.
 Pls comment if anything could use more explaning or if you disagree

**Comment by gizzon** [comment]
@charlesv99 Could you clarify on what you mean by hiding the footer? Should the footer only be hidden on the loading page?
