### ISSUE TITLE
Feature Request — Color Blindness

### ISSUE THREAD

**Issue by charlesv99** [YACS-RCOS/yacs.n#374]
The issue of dealing with customers that are color blind is a big notion in the UI world, Usually Blue is the biggest threat as its the hardest to differentiate with color blindness, But I believe the blue matches with the aesthetic of YACS well. I believe maybe adding a color-blind mode might be useful in the future rather than altering the whole color scheme.

**Comment by marchdan** [comment]
@charlesv99 I think this is a great notion. Do you think you could look through YACS and identify the parts of YACS where color differentiation (regardless of current color) is needed for its operation? (i.e Course section availability tags which differ in color based on the number of open seats). I think having this list will identify a good place for us to begin and will help to establish a hierarchy of the items for which color blindness is a necessity. Thank you!
