### ISSUE TITLE
Feature Request — Suggested schedule

### ISSUE THREAD

**Issue by shrutig27** [YACS-RCOS/yacs.n#377]
**Job**
There is a login that allows you to know what major and year the student is in.

**Describe a possible solution**
They can get a suggested schedule with the classes they require already put in.

**Context**
Given a suggested schedule, the student doesn't have to go between the requirement website and YACS to figure out what classes they are supposed to take.

**Comment by marchdan** [comment]
@123joshuawu Were you the one working on the idea of handling major templates in yacs so that we'd be able to do things like this?

**Comment by 123joshuawu** [comment]
@marchdan we started work on graduation requirements during summer but put that off in the fall, we can see if we want to pick it up again in the spring
