### ISSUE TITLE
Feature Request — Click-ability on Course Name

### ISSUE THREAD

**Issue by shrutig27** [YACS-RCOS/yacs.n#378]
**Job**
Ability to click on the course name while making the schedule to get more insight into what the class is about rather than going to Explore -> Major -> Class -> Class Description

**Describe a possible solution**
Allow the users to click on the course name and land them at the course description.

**Context**

**Comment by marchdan** [comment]
@shrutig27 Do you suggest clicking on the course name (Computer Science 1) or the shortname (CSCI-1100)?
