### ISSUE TITLE
Feature Request — Course Information

### ISSUE THREAD

**Issue by shrutig27** [YACS-RCOS/yacs.n#380]
**Job**
Give more information on the class

**Describe a possible solution**
Difficulty rating: 1-5 
Textbook Usage: Yes/No
Offered period - Spring/Fall/Both/Arch 
**Context**
Buying textbooks is expensive, knowing whether a class uses it or not based on student experience would be helpful. As well as having a difficulty rating would be insightful for students.

**Comment by marchdan** [comment]
Which pieces of information are we taking from the course catalog that are in the CSV already that can be used here? What can we get from the catalog that isn't in the CSV?
