### ISSUE TITLE
Feature Request — Course Info to Class Website

### ISSUE THREAD

**Issue by shrutig27** [YACS-RCOS/yacs.n#381]
**Job**
Using the Course Info page as the class website 

**Describe a possible solution**
Every class has a particular website which has links and all. We can populate the course info page with prof's email as well as their OH and the link to their class website. It would make contacting the professor easier!
**Context**

**Comment by marchdan** [comment]
I have been seeing commits for this issue. Can whoever has been making them create a PR draft?
