### ISSUE TITLE
Feature Request — Credit Cap

### ISSUE THREAD

**Issue by shrutig27** [YACS-RCOS/yacs.n#382]
**Job**
Alert the student if they are past the credit cap. 

**Describe a possible solution**
If the student wants to see how their schedule would look with different classes, that should be fine. However, if they're past the credit limit at RPI, there should be an alert, pop-up, or indication that they are past the credit limit. 

**Context**

**Comment by marchdan** [comment]
When this implemented, we need to be sure to differentiate between Undergrads and Grad students. The caps are different
