### ISSUE TITLE
Bug — The Course Search keeps on loading

### ISSUE THREAD

**Issue by EcneicsJiang** [YACS-RCOS/yacs.n#384]
The Course Search keeps on loading while other stuff shows up already...
It works in the past but somehow not now. The problem has been continued for a month.

![20201219205502](https://user-images.githubusercontent.com/44463735/102689871-844c5c80-423c-11eb-8551-a2ff83712960.png)

**Comment by jshom** [comment]
We're looking into the issue can you try logging out or clearing the cache. Thanks!

**Comment by marchdan** [comment]
> We're looking into the issue can you try logging out or clearing the cache. Thanks!

When I try and set a default semester, I get a 500 error:
`HTTP 500: there is no unique or exclusion constraint matching the ON CONFLICT specification`

I will look into this

**Comment by marchdan** [comment]
The "ON CONFLICT" referenced in the error can be seen here:

![Screenshot 2021-01-05 173840](https://user-images.githubusercontent.com/35609442/103707592-e61aff00-4f7c-11eb-9248-5e7a25968e25.png)

**Comment by RichtXO** [comment]
I can confirm that the loop goes forever _when_ logged in. This doesn't seem to be an issue _when not_ logged in...

**Comment by RichtXO** [comment]
Nevermind, I think clearing cookies and the cache is the fix. I legit got that loop forever, then I did something and it loaded the courses...

**Comment by marchdan** [comment]
@RichtXO When I first pull up YACS, the default redirect for yacs.cs.rpi.edu (not logged in) goes to /?semester=null because the default semester can't be set as specified above. (My cookies and cache are clear)

**Comment by 123joshuawu** [comment]
It's probably better to have the default semester be a column in the semesters_info table. Then the frontend can pull the list of semesters and request the course data for the semester with `default=true`.

**Comment by marchdan** [comment]
> It's probably better to have the default semester be a column in the semesters_info table. Then the frontend can pull the list of semesters and request the course data for the semester with `default=true`.

@123joshuawu That would make sense. As long as we can write code to change it over when the default semester is changed on the admin panel.

**Comment by 123joshuawu** [comment]
Yep I'll work on it this weekend

**Comment by EcneicsJiang** [comment]
Correct, I later found this only happens when I logged in. After I logout, it can function well.

**Comment by marchdan** [comment]
> Correct, I later found this only happens when I logged in. After I logout, it can function well.

That's weird, that happens for me logged in or logged out

**Comment by 123joshuawu** [comment]
> The "ON CONFLICT" referenced in the error can be seen here:
> 
> ![Screenshot 2021-01-05 173840](https://user-images.githubusercontent.com/35609442/103707592-e61aff00-4f7c-11eb-9248-5e7a25968e25.png)
> 
> EDIT: Not seeing issue on dev or prod in local master

okay i see now, this is because `ON CONFLICT` needs a unique constrain on the `semester` column. I migrated our table definitions to SQLAlchemy, so I guess I missed that constraint for the `admin_settings` table.
