### ISSUE TITLE
Feature Request — Dark Mode Section Boxes

### ISSUE THREAD

**Issue by keerti-sundaram** [YACS-RCOS/yacs.n#399]
[**Job**]
<img width="1190" alt="Screen Shot 2021-03-07 at 12 13 11 PM" src="https://user-images.githubusercontent.com/70778626/110248444-2841cc00-7f3f-11eb-9ecc-3c408cf45ac1.png">

Make class sections more visible in dark mode.
**Describe a possible solution**
In dark mode there is a lack of section boxes like there is in light mode (go to explore -> department). Idea is to recreate the section boxes while maintaining dark mode.
**Context**

**Comment by keerti-sundaram** [comment]
Fixed Boxes, so now they appear. Next step is to work on the hover mechanism.
<img width="1059" alt="Screen Shot 2021-03-07 at 12 19 12 PM" src="https://user-images.githubusercontent.com/70778626/110248470-5a532e00-7f3f-11eb-8f0c-22addf5d88a4.png">

**Comment by RichtXO** [comment]
@keerti-sundaram Normally, you would want to put the pic of your implementation in the Pull Request. Your pull request doesn't have to be finished.
