### ISSUE TITLE
Bug — CourseSelection not pulling data

### ISSUE THREAD

**Issue by RichtXO** [YACS-RCOS/yacs.n#404]
**Describe the bug**
Refreshing the page with any semester selected leads to an "oops, no result" error in the course selection section

**To Reproduce**
1. Go to the website
2. Refresh page

**Expected behavior**
Should load the semester course data.

**Screenshots**
![image](https://user-images.githubusercontent.com/22281588/108571921-31942d00-72df-11eb-8ff0-cb0816f4719a.png)

**Comment by marchdan** [comment]
![Screenshot from 2021-02-19 18-31-29](https://user-images.githubusercontent.com/35609442/108572713-e713b000-72e0-11eb-91c6-f09d5c54bdca.png)

**Comment by marchdan** [comment]
@RichtXO ^^^

**Comment by RichtXO** [comment]
Might have an actual fix now, maybe. The last one patched the issue of not displaying anything data when refresh, but when going into the main page, going into Explore, and back to the main page, the data doesn't show.

**Comment by marchdan** [comment]
> Might have an actual fix now, maybe. The last one patched the issue of not displaying anything data when refresh, but when going into the main page, going into Explore, and back to the main page, the data doesn't show.

What exactly do the header bar "Schedule" button and the Explorer "YACS" button do that could cause this issue?

**Comment by marchdan** [comment]
> So if you load data, go into the Explorer page, then back to the main viewing page, courses don't load, if that's what you're asking.

@RichtXO Right, but if you then refresh the page, it goes. So what happens differently between loading the page and nagivating there from Course explorer

**Comment by RichtXO** [comment]
Oh ok! This is a Vuex problem! I think it's doing a commit multiple times. For example, in `App.vue`, it's already storing courses in the cookie, and  `Course.Scheduler.vue` (or the other file, currently forgetting which file was) was also commiting to store courses. The explorer page didn't have any commits, hence why it's working as intended. This problem was fixed in Josh's PR, where he changed how the site uses Vuex.
