### ISSUE TITLE
Distribution — RPI:Pull data from RPI catalog to provide more metadata for courses

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#41]
This has already been implemented in old YACS in Ruby, we just need to migrate it to Python.
It is located in `pipelines/rpi/adapters/acalog-rpi`

It appears that there is an API we can query for RPI catalog information at
http://rpi.apis.acalog.com

**Comment by jshom** [comment]
To clarify: this functionality should be only in the parser, *not* python api
