### ISSUE TITLE
Bug — Export to Image not working

### ISSUE THREAD

**Issue by marchdan** [YACS-RCOS/yacs.n#420]
**Describe the bug**
The schedule view image export does nothing.

**To Reproduce**
1. Go to YACS
2. Add some courses
3. Click on the 'Export data' dropdown
4. Click on 'Export to image'
5. Notice that no image is downloaded

**Expected behavior**
Schedule image should export as added in #339 

**Additional context**
This problem persists both logged out and logged in.

**Comment by RichtXO** [comment]
I suspect the error occurs when there are multiple sub semesters (like in Arch, there are 2 calendars in one).  The code for this is in [utils.js](https://github.com/YACS-RCOS/yacs.n/blob/master/src/web/src/utils.js).

**Comment by marchdan** [comment]
> I suspect the error occurs when there are multiple sub semesters (like in Arch, there are 2 calendars in one). The code for this is in [utils.js](https://github.com/YACS-RCOS/yacs.n/blob/master/src/web/src/utils.js).

Yes, this is the issue, lol. I did not even think to try on Fall 2021.

**Comment by marchdan** [comment]
@RichtXO And utils.js is called from within CourseScheduler.vue
