### ISSUE TITLE
Feature Request — Courses That Fit Given Schedule

### ISSUE THREAD

**Issue by taniacao12** [YACS-RCOS/yacs.n#442]
**Job**
Display only courses that fit into your schedule

**Describe a possible solution**
Add a button to show only courses with time slots that don't overlap with those already selected
This should filter out courses in each department but also entire departments from the "Filter Department" dropdown

**Context**
When searching for electives, it is difficult to find classes that fit without going through each and every department and clicking on every course

**Comment by RichtXO** [comment]
Reference to issues #52 and #332 and PR #398 

We are working on this feature, and hopefully, get this online before Fall registration. Thx for reporting!
