### ISSUE TITLE
Discussion (Pre Feature Request) — Schedule events scroll bar and info

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#449]
**Job**
Discuss and propose changes to event info based on sizing/device differences

Moving discussion from #448 about event info and scroll bars here.

---

> > @Viyerelu23333 There are 3/4 options for the course blocks:
> > > 1. Scroll bars on blocks that have more data than can visibly fit in the window
> > > 2. The Course blocks expand when you hover over them so you can see all of their content
> > > 3. You can click on a course block and a pop-up comes up with all of the schedule relevant info for that section of the course
> > > 4. Noting happens and you see what you see.
> > 
> > 
> > I personally think option 3 would fit our needs and aesthetic the best atm. Number 1 is what we have right now, and number 2 is a feature that was being worked on for old YACS.
> 
> Oh I see. Totally agree that we might need option 3. I tried to add a `hover` as option 2, and this is not friendly to mobile users.

Interesting, gonna make an another issue for this to investigate. For the issue (#444) however, I think we can leave the scroll bars and more info the same as it is and handle that separately.

**Comment by marchdan** [comment]
The original issue was being able to screenshot/export your YACS schedule and see all relevant info if possible, so the following items need to be top priority visible:
```
Course Label (I.e. CSCI 1100)
Course Type (Lcture/Lab/Test/etc.)
Location (DCC 308)
```
If the screen is large enough to fit a course name it can be whatever fits height-wise of:
```
Course Name (Computer Science 1)
Course Label (I.e. CSCI 1100)
Course Type (Lecture/Lab/Test/etc.)
Location (DCC 308)
Instructors (Turner)
CRN (123456)
```

Beyond that, I think the user would be ok clicking on a course block to see additional info. Option 3 is equally friendly to mobile and desktop use of said feature. Scroll bars are ok on mobile, but a little unwieldy atm and hover elements will not behave nicely with mobile.

**Comment by 123joshuawu** [comment]
Linking some previous thoughts in #227
