### ISSUE TITLE
Scheduling — Show sub semesters

### ISSUE THREAD

**Issue by 123joshuawu** [YACS-RCOS/yacs.n#47]
Should be a different schedule for each subsemester with each schedule containing courses in that subsemester and any encompassing subsemester
Users can toggle which schedule they are viewing using a dropdown menu

**Comment by jshom** [comment]
In a given semester, for example summer, there can be classes that only go on for 6 of the 12 weeks along with full semester classes. To gain understanding of the entire semester's schedule we need a way to show both.
Note: this may require tweaking the ics download feature

Also here are notes on the design from before:
```
YACS Arch Tentative Wireframe
Course Selection View
Drop down menu / Checkboxes to allow for users to choose between viewing courses for Summer Session 1 / 2 / Full Term
Drop down - Just choose between Sessions 1 and 2 (Full term displayed on both)
Checkboxes - 3 Choices, as listed above
Individual courses are tagged as 12 week or 6 week to signify Full Term of just the Session chosen
Schedule View
Similar to Course Selection view, drop down menu is used to swap views between Session 1 and Session 2
Both 12 week and 6 week courses that will be taken in that Session are displayed just like the normal YACS Schedule view, as both sessions are essentially separate 'semesters'```
