### ISSUE TITLE
Admin Panel needs some work

### ISSUE THREAD

**Issue by RichtXO** [YACS-RCOS/yacs.n#490]
**Job**
It does its job, but a new interface could bring a better experience.

**Describe a possible solution**
Your imagination is the limit! 

**Context**
Open to any cool layouts and UX redesigns!

**Comment by SamooMei** [comment]
![Stuffies](https://user-images.githubusercontent.com/43279636/135726973-9fd3d4e1-b0e1-42af-952d-8ca42f0c318c.png)

I'm a real sucker for centered stuff and buttons so probably something like this?

**Comment by 123joshuawu** [comment]
Some previous work for reference https://github.com/YACS-RCOS/yacs.n/pull/75
