### ISSUE TITLE
DevOps — Automate course updates across semesters

### ISSUE THREAD

**Issue by RichtXO** [YACS-RCOS/yacs.n#520]
**Job**
Have Spring 2022 data in ./rpi_data/

**Describe a possible solution**
Use similar scripts to parse these 3 sites:

- https://sis.rpi.edu/reg/zfs202205.htm
- https://sis.rpi.edu/reg/zfs20220502.htm
- https://sis.rpi.edu/reg/zfs20220503.htm

**Context**
follow standard in ./rpi_data/ folder

**Comment by jaw12346** [comment]
Link pattern
01 (spring)
05, 0502, 0503 (summer)
09 (fall)


Depending on the current month, use a conditional to choose between spring, summer, and fall.
Follow the provided manual code and add conditionals.

Ex: It's spring: check for spring and summer
    It's summer: check for summer and fall

**Comment by jaw12346** [comment]
See branch "#520 - Automate Course Updates Across Semesters" for our first draft script. Sources are attached to the first commit (two commits have been made). The first commit is the script, second commit fixes style and syntax issues.
