### ISSUE TITLE
Feature Request — Rate My Professors

### ISSUE THREAD

**Issue by ethanz2003** [YACS-RCOS/yacs.n#594]
**Job**
Create a Rate My Professors display within the YACS calendar.

**Describe a possible solution**
Create some sort of link that will display a popup of overall RMP stats.
Potentially find a way to get course specific stats for a professor who teaches multiple courses
Provide a link to RMP site directly within the popup to view professor's site.

**Comment by DarknessUnder** [comment]
Closed due to the concern that we do not want risk endorse a third party website and judge professor
