### ISSUE TITLE
Scheduling — Semester Parts

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#63]
Currently we have date ranges in the dropdown for partial semesters, this does not make perfect sense as in a semester with 3 date ranges (full, first half, second half) during a semester, there would only really be two separate schedules. 

To solve this, lets create a mapping from date range -> semester part.
Example:
Course (05/25-08/20) is in semester parts 1 & 2
Course (05/25-07/10) is in semester part 1

We will need to be able to manipulate the scheduling mappings in the admin panel.
We should able to:
1. Add a date range mapping (name and date range)
2. Edit a date range mapping (name and date range)
3. Ignore a date range mapping (ignore flag)

This should reside in a table date_range_semester_part that will have a wrapper in the src/db/ wrappers directory.
NOTE: add the `create table` statement in the src/data/schema/ directory and add the script to execute in the src/data/build.sh

At completion, in the example of RPI's summer semester, we should be able to see summer part 1, summer part 2 in the dropdown if someone selects a partial semester class. If all selected classes are full semester, then only show the full summer semester.

**Comment by CoreyBuckley** [comment]
> Course (05/25-08/20) is in semester parts 1 & 2 & full

Wouldn't `full` be redundant here? Full would just be defined as a course that spans all possible parts.

**Comment by jshom** [comment]
Yes, #59 would be implemented with this.
I agree it would be redundant, checking if exists in all unique semester parts would be equivalent check.

**Comment by CoreyBuckley** [comment]
I'm confused on what the use case of this is. If you implement this mapping between dates, then on the backend:

- We have two new tables. 
    - `date_range_semester_part (semester_name varchar(255) PK, start_date date PK, end_date date PK)`
    - `course_date_parts (course FK, date_range_semester_part FK)` and the bridge table

Then logic will have to be added to the Python CSV parser to populate these tables.

So, then on the frontend, you would have the dropdown options be what comes from something like `SELECT start_date . ' - ' . end_date FROM date_range_semester_part WHERE semester_name='SUMMER 2020'`


Why not just get rid of the full term option on the frontend instead?

**Comment by jshom** [comment]
1. This would not require changes to the CSV parser, this is only to provide customization on top of simple dates that are hard to read.
2. there would not be changes to course_date_parts, that would be redundant. This is only renaming date ranges. 

To get the mapping we would do a join on this table with out existing query.


So in summary:
- point is semantics in front end
- second part is simplifying options in scheduling

Please let me know if I can expand on something else

**Comment by CoreyBuckley** [comment]
Thanks! 😄
