### ISSUE TITLE
Scheduling — Search: UX Tweaks

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#68]
Change both selects (department and date range) to vue selects to allow text search for options in dropdown. https://vue-select.org. Quicker to search by department if we can type a few letters and hit enter without using the mouse. 
![Screen Shot 2020-03-22 at 2 52 36 PM](https://user-images.githubusercontent.com/11034221/77257783-cc5a3680-6c4c-11ea-9591-bea3aaf3495b.jpg)

**Comment by 123joshuawu** [comment]
#182 Completes item 1

**Comment by erinsong** [comment]
ok i can't figure out how to assign this issue to myself, but im starting on this

**Comment by erinsong** [comment]
ok wait im a little confused bc this already works for me. when i type csci in the search all csci courses come up & when i type "cs" for example it highlights csci and from there I'm able to click enter to filter & show all the csci courses.

**Comment by jshom** [comment]
Ah gocha, yep, removing that from the issue :+1:

**Comment by erinsong** [comment]
Oops I didn't explain that right, I meant to explicitly say the vue select also works for me. Did someone already do this and it wasn't checked off bc I haven't changed anything to the code and I'm able to "type a few letters and hit enter without using the mouse"

**Comment by marchdan** [comment]
@jshom Is this still relevant?
