### ISSUE TITLE
Feature Request — Final Schedule

### ISSUE THREAD

**Issue by chavab0809** [YACS-RCOS/yacs.n#690]
**Job**
Create a page where the user can input their current classes (Dept, Course#, Section) then we generate a google calendar like schedule that will have the times, dates and locations.

Currently under:
src/web/src/pages

Here is a rough draft of how the page will be set up:

![Psoft-12](https://user-images.githubusercontent.com/123212886/231295097-9bbe79ad-394a-45b0-a444-c6e2d9959ffc.jpg)

**Comment by jonha1** [comment]
Done!
