### ISSUE TITLE
Feature Request — Semester Dropdown Menu Sorting

### ISSUE THREAD

**Issue by martig7** [YACS-RCOS/yacs.n#789]
**Describe the Feature**
When selecting a semester, the dropdown menu is sorted strangely.

**Expected behavior**
Semesters should be sorted by time, YACS currently only shows Summer 2022, Summer 2023, Fall 2023, and Spring 2023 in that order, but spring should go before summer.

**Screenshots**
![image](https://github.com/YACS-RCOS/yacs.n/assets/143552868/75485317-114b-4bac-ada6-067a7453b4fd)

**Comment by Kagiri2** [comment]
There are two of these issues. The other one has the pull req attached to it.
