### ISSUE TITLE
Choosing default semester on website's admin page doesn't work

### ISSUE THREAD

**Issue by jonha1** [YACS-RCOS/yacs.n#791]
<img width="1439" alt="image" src="https://github.com/YACS-RCOS/yacs.n/assets/78988736/d3452163-df72-4615-aff0-e0ab16032636">

When selecting a default semester, we get an error "connection already closed."

The cause is unknown.

**Comment by Kagiri2** [comment]
It works on my admin page.

![image](https://github.com/YACS-RCOS/yacs.n/assets/37049496/3c5e4062-2a7a-40a9-b9cf-c2035e8d8939)
