### ISSUE TITLE
Bug — Location often appears as TBA for classes

### ISSUE THREAD

**Issue by bnavac** [YACS-RCOS/yacs.n#799]
**Describe the bug**
The location for many classes often appears as TBA. However, many classes have a location that is known in SIS, but still is not on YACS.

**To Reproduce**
1. Add a class to a schedule.

**Expected behavior**
When a user adds a class, a location that matches the SIS info should appear.

**Screenshots**
![image](https://github.com/YACS-RCOS/yacs.n/assets/70664095/2c942cb1-751f-412e-8832-7c948ee6b025)

**Comment by martig7** [comment]
This was fixed with the previous web scrape update.
