### ISSUE TITLE
Feature Request — user profile page and settings

### ISSUE THREAD

**Issue by jvmespark** [YACS-RCOS/yacs.n#803]
**Job**
a profile page for logged in users as well as settings to change their email, name, major and other details. 

**Describe a possible solution**
dynamically generate user profile pages using slug routing.

**Comment by c-jimmy1** [comment]
This issue already exists at: https://github.com/YACS-RCOS/yacs.n/issues/501
Pull request draft located at: https://github.com/YACS-RCOS/yacs.n/pull/654

Closing this issue.
