### ISSUE TITLE
Feature Request — Add a Profile Page

### ISSUE THREAD

**Issue by Kagiri2** [YACS-RCOS/yacs.n#827]
**Job**
Currently, when you make an account you are unable to change your password. The Major and Degree form elements are also useless as we do not use them for anything. Addressing this can be useful for future features.

**Describe a possible solution**
Make a profile page that can be accessed when the user is logged in. Here the user can look at their profile and change their settings. 

**Context**

**Comment by ethan2917** [comment]
This is an issue thats currently being worked on within PR: https://github.com/YACS-RCOS/yacs.n/pull/654. Closing this branch to avoid duplicates, thanks!
