### ISSUE TITLE
Feature Request — Delete Account

### ISSUE THREAD

**Issue by Kagiri2** [YACS-RCOS/yacs.n#828]
**Job**
Allow the user to be able to delete their account 

**Describe a possible solution**
When the user is logged in allow the user to delete their account by typing their password again.

**Context**

**Comment by ethan2917** [comment]
This is currently being worked on in PR: https://github.com/YACS-RCOS/yacs.n/pull/654
I'm going to close this issue for you to prevent duplicates. Thanks!
