### ISSUE TITLE
Scheduling — Course list isn't mobile responsive

### ISSUE THREAD

**Issue by CoreyBuckley** [YACS-RCOS/yacs.n#83]
At breakpoint `md` or width `768px` the course list looks like this.

![image](https://user-images.githubusercontent.com/28029704/77988752-15645780-72eb-11ea-9568-5585eab0050b.png)

It doesn't fix itself until ~ 1270px width. The tab pane is exceeding the tab container for some reason.

At smaller than the `md` breakpoint, the course list is almost mobile-friendly except the courses are missing due to the height being 0 for some reason. `min-height: 200px` on the scroll box is a possible fix for this.

![image](https://user-images.githubusercontent.com/28029704/77988969-8d328200-72eb-11ea-8929-7f8d74c0eb32.png)

**Comment by jshom** [comment]
if this can be fixed in 5 min, go at it. If it takes longer, I wouldn't worry. Given we are pre beta its likely to change again
