### ISSUE TITLE
Schedule — Selecting multiple sections of the same course

### ISSUE THREAD

**Issue by tygentry** [YACS-RCOS/yacs.n#95]
When selecting multiple sections of the same course, if they conflict, the section is not added, and if they don't, both sections show up on the schedule viewer as opposed to creating additional schedules, which should occur in both cases. Also selecting a section of a different course that conflicts with only one of the multiple course sections doesn't generate an alternate schedule, showing a schedule conflict and not selecting the course.

**Comment by 123joshuawu** [comment]
Yeah I've been meaning to get to this, believe this stems from #52

**Comment by jshom** [comment]
Closed since 52 would fix this
